/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) pendulum_ode_constr_h_e_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s1[3] = {0, 0, 0};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};

/* pendulum_ode_constr_h_e_fun:(i0[2],i1[],i2[],i3[])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6;
  a0=-5.8691993515635636e+02;
  a1=arg[0]? arg[0][0] : 0;
  a2=9.8174770424681035e-01;
  a2=(a1-a2);
  a2=casadi_sq(a2);
  a3=arg[0]? arg[0][1] : 0;
  a4=5.5555555555555536e+00;
  a4=(a3-a4);
  a4=casadi_sq(a4);
  a2=(a2+a4);
  a4=1.9748555121383529e+01;
  a2=(a2/a4);
  a2=(-a2);
  a2=exp(a2);
  a0=(a0*a2);
  a2=-1.1713755758009473e+01;
  a5=8.8357293382212931e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-9.2592592592592595e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a2=(a2*a5);
  a0=(a0+a2);
  a2=-1.9786298728277180e+02;
  a5=1.2762720155208536e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=4.0740740740740744e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a2=(a2*a5);
  a0=(a0+a2);
  a2=-3.7310465009282019e+01;
  a5=2.9452431127404310e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-7.0370370370370372e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a2=(a2*a5);
  a0=(a0+a2);
  a2=3.7397023325470371e+01;
  a5=1.1780972450961724e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-7.7777777777777777e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a2=(a2*a5);
  a0=(a0+a2);
  a2=1.1143781947405346e+01;
  a5=5.8904862254808621e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-5.5555555555555554e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a2=(a2*a5);
  a0=(a0+a2);
  a2=2.0273390289965704e+02;
  a5=6.8722339297276724e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=6.2962962962962941e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a2=(a2*a5);
  a0=(a0+a2);
  a2=5.8181487956225055e+02;
  a5=9.6390366394000115e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=4.7997524393445161e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a2=(a2*a5);
  a0=(a0+a2);
  a2=7.1755547163589817e-01;
  a5=1.3858021222930859e+00;
  a1=(a1-a5);
  a1=casadi_sq(a1);
  a5=9.2091494675663410e-01;
  a3=(a3-a5);
  a3=casadi_sq(a3);
  a1=(a1+a3);
  a1=(a1/a4);
  a1=(-a1);
  a1=exp(a1);
  a2=(a2*a1);
  a0=(a0+a2);
  a2=4.0943773690093094e-01;
  a0=(a0+a2);
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int pendulum_ode_constr_h_e_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int pendulum_ode_constr_h_e_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int pendulum_ode_constr_h_e_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pendulum_ode_constr_h_e_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int pendulum_ode_constr_h_e_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pendulum_ode_constr_h_e_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void pendulum_ode_constr_h_e_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void pendulum_ode_constr_h_e_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int pendulum_ode_constr_h_e_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int pendulum_ode_constr_h_e_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real pendulum_ode_constr_h_e_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pendulum_ode_constr_h_e_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pendulum_ode_constr_h_e_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pendulum_ode_constr_h_e_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pendulum_ode_constr_h_e_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int pendulum_ode_constr_h_e_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
