/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) pendulum_ode_constr_h_e_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s1[3] = {0, 0, 0};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};

/* pendulum_ode_constr_h_e_fun:(i0[2],i1[],i2[],i3[])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7;
  a0=-1.3622047244094490e+05;
  a1=arg[0]? arg[0][0] : 0;
  a2=5.1541754472957546e-01;
  a2=(a1-a2);
  a2=casadi_sq(a2);
  a3=arg[0]? arg[0][1] : 0;
  a4=-4.5679012345679020e+00;
  a4=(a3-a4);
  a4=casadi_sq(a4);
  a2=(a2+a4);
  a4=1.2543180363608318e+01;
  a2=(a2/a4);
  a2=(-a2);
  a2=exp(a2);
  a2=(a0*a2);
  a5=1.4358060174609601e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-5.4732510288065841e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=1.1207647131489466e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-3.0823553320123978e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=1.1581554948536590e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-3.1229995427526287e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=1.6797089627347772e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-3.7814357567443988e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=1.7573667401214876e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-3.8139511253365850e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=6.1982411210504185e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-4.6857694457145769e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=6.0285444963905699e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-4.6776406035665294e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=-2.4014299322705312e+04;
  a6=9.6027197321641133e-01;
  a6=(a1-a6);
  a6=casadi_sq(a6);
  a7=2.3731138545953350e+00;
  a7=(a3-a7);
  a7=casadi_sq(a7);
  a6=(a6+a7);
  a6=(a6/a4);
  a6=(-a6);
  a6=exp(a6);
  a5=(a5*a6);
  a2=(a2+a5);
  a5=-1.1488322927518420e+04;
  a6=2.1667478628884682e-01;
  a6=(a1-a6);
  a6=casadi_sq(a6);
  a7=3.4735558603871368e+00;
  a7=(a3-a7);
  a7=casadi_sq(a7);
  a6=(a6+a7);
  a6=(a6/a4);
  a6=(-a6);
  a6=exp(a6);
  a5=(a5*a6);
  a2=(a2+a5);
  a5=1.7698303340230584e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=3.5263933343494358e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=5.3698914955921728e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-4.5760300767159476e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=-7.3080832005858436e+04;
  a6=1.3002404653315667e+00;
  a6=(a1-a6);
  a6=casadi_sq(a6);
  a7=1.9036732205456470e+00;
  a7=(a3-a7);
  a7=casadi_sq(a7);
  a6=(a6+a7);
  a6=(a6/a4);
  a6=(-a6);
  a6=exp(a6);
  a5=(a5*a6);
  a2=(a2+a5);
  a5=9.2058022032987041e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=2.4218869074836178e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=1.0025523186825094e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=2.3040186963369393e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=-1.0676948874616188e+05;
  a6=3.1810926588778482e-01;
  a6=(a1-a6);
  a6=casadi_sq(a6);
  a7=-4.2651018645531682e+00;
  a7=(a3-a7);
  a7=casadi_sq(a7);
  a6=(a6+a7);
  a6=(a6/a4);
  a6=(-a6);
  a6=exp(a6);
  a5=(a5*a6);
  a2=(a2+a5);
  a5=-5.3842651845554559e+04;
  a6=4.8723064775217678e-01;
  a6=(a1-a6);
  a6=casadi_sq(a6);
  a7=-4.5435147081237623e+00;
  a7=(a3-a7);
  a7=casadi_sq(a7);
  a6=(a6+a7);
  a6=(a6/a4);
  a6=(-a6);
  a6=exp(a6);
  a5=(a5*a6);
  a2=(a2+a5);
  a5=-9.1179007014600080e+04;
  a6=1.3058011456876520e-01;
  a6=(a1-a6);
  a6=casadi_sq(a6);
  a7=-3.4644109129705845e+00;
  a7=(a3-a7);
  a7=casadi_sq(a7);
  a6=(a6+a7);
  a6=(a6/a4);
  a6=(-a6);
  a6=exp(a6);
  a5=(a5*a6);
  a2=(a2+a5);
  a5=1.2519200705131690e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=1.9280597469897902e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=-1.1538962417343946e+05;
  a6=8.9066759496610040e-02;
  a6=(a1-a6);
  a6=casadi_sq(a6);
  a7=-2.7653304882385825e+00;
  a7=(a3-a7);
  a7=casadi_sq(a7);
  a6=(a6+a7);
  a6=(a6/a4);
  a6=(-a6);
  a6=exp(a6);
  a5=(a5*a6);
  a2=(a2+a5);
  a5=-2.3551200277622129e+03;
  a6=8.1511904116273259e-01;
  a6=(a1-a6);
  a6=casadi_sq(a6);
  a7=-4.9509729207945954e+00;
  a7=(a3-a7);
  a7=casadi_sq(a7);
  a6=(a6+a7);
  a6=(a6/a4);
  a6=(-a6);
  a6=exp(a6);
  a5=(a5*a6);
  a2=(a2+a5);
  a5=-9.1099108388741937e+04;
  a6=1.4158642672184467e+00;
  a6=(a1-a6);
  a6=casadi_sq(a6);
  a7=1.6963877457704619e+00;
  a7=(a3-a7);
  a7=casadi_sq(a7);
  a6=(a6+a7);
  a6=(a6/a4);
  a6=(-a6);
  a6=exp(a6);
  a5=(a5*a6);
  a2=(a2+a5);
  a5=2.6652916189513015e-02;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-1.5216176395874630e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=1.5156688922302564e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=1.3224610069603209e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=1.5332137974916984e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=1.1842706904435314e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=1.5550730237190686e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=7.2092668800487658e-01;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=-1.1415735594857876e+05;
  a6=1.5493205957644975e+00;
  a6=(a1-a6);
  a6=casadi_sq(a6);
  a7=8.9163237311385402e-01;
  a7=(a3-a7);
  a7=casadi_sq(a7);
  a6=(a6+a7);
  a6=(a6/a4);
  a6=(-a6);
  a6=exp(a6);
  a5=(a5*a6);
  a2=(a2+a5);
  a5=1.5389662254462695e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=1.0867245846669711e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a0=(a0*a5);
  a2=(a2+a0);
  a0=-1.7906273958782673e+04;
  a5=1.5700293364009537e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=5.2583447645176129e-01;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a0=(a0*a5);
  a2=(a2+a0);
  a0=7.8995433789954346e+04;
  a5=1.2923788137936526e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=3.5832952293857634e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=7.7405046268613980e+04;
  a6=9.1866274434501338e-01;
  a6=(a1-a6);
  a6=casadi_sq(a6);
  a7=-5.0241325001270134e+00;
  a7=(a3-a7);
  a7=casadi_sq(a7);
  a6=(a6+a7);
  a6=(a6/a4);
  a6=(-a6);
  a6=exp(a6);
  a5=(a5*a6);
  a2=(a2+a5);
  a5=4.6134472195660658e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-4.4459686023472038e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=5.7236658147982988e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-4.6166742874561804e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=2.5023061602384522e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-4.0131077579637253e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=1.9903400722816195e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-3.8424020728547470e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=7.2041304782655759e+04;
  a6=1.3863351370516481e+00;
  a6=(a1-a6);
  a6=casadi_sq(a6);
  a7=-5.4244779759183057e+00;
  a7=(a3-a7);
  a7=casadi_sq(a7);
  a6=(a6+a7);
  a6=(a6/a4);
  a6=(-a6);
  a6=exp(a6);
  a5=(a5*a6);
  a2=(a2+a5);
  a5=3.2577916982721306e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=3.3028501752781576e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=7.6929136512464902e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=2.6383173296753544e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=2.4390294527381695e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-4.0374942844078641e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=2.2146847625098945e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-3.9399481786313073e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=1.0371627602091791e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-5.1501295534217348e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=5.1631420043185019e+04;
  a6=8.0150496167024757e-02;
  a6=(a1-a6);
  a6=casadi_sq(a6);
  a7=-2.3426306965401622e+00;
  a7=(a3-a7);
  a7=casadi_sq(a7);
  a6=(a6+a7);
  a6=(a6/a4);
  a6=(-a6);
  a6=exp(a6);
  a5=(a5*a6);
  a2=(a2+a5);
  a5=1.0431069357622361e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-2.7572016460905360e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=2.6058498634207328e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-4.1187827058883295e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=1.1338035498459744e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-5.2476756591982934e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=8.9814575130704288e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=2.4462734339277539e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=3.5089810522884041e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-4.2813595488492604e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=3.2846363620601293e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-4.2325864959609829e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=9.4474041773906925e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=2.3649850124472884e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=3.9231558650175274e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-4.3545191281816802e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=7.6123796598824942e-02;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-2.4401768023167207e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=1.4352307746655030e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-3.3749936493420716e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=1.0085923680348091e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-2.8547477518670927e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=1.5761652595524964e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-3.5131839658588628e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=1.4555560201049877e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=1.6150993242899965e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=1.2294856014903415e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=1.9524462734339281e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=1.3727210575591631e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=1.7248386932886248e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=4.1609228871398014e-02;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-1.7085810089925317e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=2.9341766973949598e+04;
  a6=2.0900488234941859e-02;
  a6=(a1-a6);
  a6=casadi_sq(a6);
  a7=-1.1233043743331805e+00;
  a7=(a3-a7);
  a7=casadi_sq(a7);
  a6=(a6+a7);
  a6=(a6/a4);
  a6=(-a6);
  a6=exp(a6);
  a5=(a5*a6);
  a2=(a2+a5);
  a5=1.4883448594460433e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=1.5256820606614863e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=1.4572817484913592e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=1.5500685871056241e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=2.1025124173957568e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-4.0700096530000520e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=1.4175899956048181e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=1.5988416399939069e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=1.4831676742869293e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=1.3956205862927398e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=1.5044516577188425e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=1.2330437433318089e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=1.5337890402871555e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=8.8350353096580747e-01;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=1.5475948673781261e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=5.9086521363613187e-01;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=1.5286118551280414e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=8.1847279378143334e-01;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=1.5406919538326409e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=6.9654016156073695e-01;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a0*a5);
  a2=(a2+a5);
  a5=1.4705123327868728e+00;
  a1=(a1-a5);
  a1=casadi_sq(a1);
  a5=1.4281359548849277e+00;
  a3=(a3-a5);
  a3=casadi_sq(a3);
  a1=(a1+a3);
  a1=(a1/a4);
  a1=(-a1);
  a1=exp(a1);
  a0=(a0*a1);
  a2=(a2+a0);
  a0=-2.1598771075806150e+02;
  a2=(a2+a0);
  if (res[0]!=0) res[0][0]=a2;
  return 0;
}

CASADI_SYMBOL_EXPORT int pendulum_ode_constr_h_e_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int pendulum_ode_constr_h_e_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int pendulum_ode_constr_h_e_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pendulum_ode_constr_h_e_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int pendulum_ode_constr_h_e_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pendulum_ode_constr_h_e_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void pendulum_ode_constr_h_e_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void pendulum_ode_constr_h_e_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int pendulum_ode_constr_h_e_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int pendulum_ode_constr_h_e_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real pendulum_ode_constr_h_e_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pendulum_ode_constr_h_e_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pendulum_ode_constr_h_e_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pendulum_ode_constr_h_e_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pendulum_ode_constr_h_e_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int pendulum_ode_constr_h_e_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
