/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) pendulum_ode_constr_h_e_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s1[3] = {0, 0, 0};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};

/* pendulum_ode_constr_h_e_fun:(i0[2],i1[],i2[],i3[])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7;
  a0=-2.3100161748032247e+03;
  a1=arg[0]? arg[0][0] : 0;
  a2=1.7410681942502026e-01;
  a2=(a1-a2);
  a2=casadi_sq(a2);
  a3=arg[0]? arg[0][1] : 0;
  a4=9.6067672610882475e+00;
  a4=(a3-a4);
  a4=casadi_sq(a4);
  a2=(a2+a4);
  a4=2.3600066120680570e+01;
  a2=(a2/a4);
  a2=(-a2);
  a2=exp(a2);
  a0=(a0*a2);
  a2=-4.2869166036947083e+05;
  a5=1.3522040645211928e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=3.9277549154092366e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a2=(a2*a5);
  a0=(a0+a2);
  a2=-1.2076153460661296e+03;
  a5=3.7045636027438233e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-7.1833561957018750e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a2=(a2*a5);
  a0=(a0+a2);
  a2=-2.4360471988565438e+04;
  a5=1.1865341394295434e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=5.2446273433927750e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a2=(a2*a5);
  a0=(a0+a2);
  a2=-8.2333272092695688e+02;
  a5=8.3985448136738849e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-9.6250571559213540e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a2=(a2*a5);
  a0=(a0+a2);
  a2=-1.3967085033768658e+03;
  a5=2.9912625363770002e-02;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-4.4398719707361689e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a2=(a2*a5);
  a0=(a0+a2);
  a2=-4.5414205774628417e+03;
  a5=7.5395155724579266e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=7.2473708276177398e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a2=(a2*a5);
  a0=(a0+a2);
  a2=1.1379190238423214e+03;
  a5=8.6976710673115853e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-9.3324188385916784e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a2=(a2*a5);
  a0=(a0+a2);
  a2=2.0999039798119338e+03;
  a5=2.7731320984197400e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=-5.5908541333594481e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a2=(a2*a5);
  a0=(a0+a2);
  a2=5.2731971155140236e+03;
  a5=3.2331539737107617e-01;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=8.7478800333119100e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a2=(a2*a5);
  a0=(a0+a2);
  a2=5.4382826475849732e+04;
  a5=1.2892817953090487e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=4.3401863966589431e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a2*a5);
  a0=(a0+a5);
  a5=1.3313866143382744e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=4.0812230063131478e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a2*a5);
  a0=(a0+a5);
  a5=1.3709145614766922e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=3.8247534113021029e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a2*a5);
  a0=(a0+a5);
  a5=1.4078888934605549e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=3.5704489480491075e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a2*a5);
  a0=(a0+a5);
  a5=5.3747262060963178e+04;
  a6=1.2603993658308712e+00;
  a6=(a1-a6);
  a6=casadi_sq(a6);
  a7=4.4878331706943921e+00;
  a7=(a3-a7);
  a7=casadi_sq(a7);
  a6=(a6+a7);
  a6=(a6/a4);
  a6=(-a6);
  a6=exp(a6);
  a5=(a5*a6);
  a0=(a0+a5);
  a5=1.3039717345901454e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=4.2271271255226806e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a2*a5);
  a0=(a0+a5);
  a5=1.3449509856609159e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=3.9691463248447776e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a5=(a2*a5);
  a0=(a0+a5);
  a5=1.3833625515783818e+00;
  a5=(a1-a5);
  a5=casadi_sq(a5);
  a6=3.7135346028323704e+00;
  a6=(a3-a6);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a5/a4);
  a5=(-a5);
  a5=exp(a5);
  a2=(a2*a5);
  a0=(a0+a2);
  a2=2.0393158169589016e+04;
  a5=1.4192285334179742e+00;
  a1=(a1-a5);
  a1=casadi_sq(a1);
  a5=3.4599814006110505e+00;
  a3=(a3-a5);
  a3=casadi_sq(a3);
  a1=(a1+a3);
  a1=(a1/a4);
  a1=(-a1);
  a1=exp(a1);
  a2=(a2*a1);
  a0=(a0+a2);
  a2=8.8579022762614628e+00;
  a0=(a0+a2);
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int pendulum_ode_constr_h_e_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int pendulum_ode_constr_h_e_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int pendulum_ode_constr_h_e_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pendulum_ode_constr_h_e_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int pendulum_ode_constr_h_e_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pendulum_ode_constr_h_e_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void pendulum_ode_constr_h_e_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void pendulum_ode_constr_h_e_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int pendulum_ode_constr_h_e_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int pendulum_ode_constr_h_e_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real pendulum_ode_constr_h_e_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pendulum_ode_constr_h_e_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pendulum_ode_constr_h_e_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pendulum_ode_constr_h_e_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pendulum_ode_constr_h_e_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int pendulum_ode_constr_h_e_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
