/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) pendulum_ode_constr_h_e_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

static const casadi_int casadi_s0[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s1[3] = {0, 0, 0};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};

/* pendulum_ode_constr_h_e_fun:(i0[2],i1[],i2[],i3[])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a3, a4, a5, a6, a7, a8, a9;
  a0=1.;
  a1=-3.1630959510803223e+00;
  a2=-1.5751074552536011e+00;
  a3=-2.5045608520507812e+01;
  a4=1.0732157707214355e+01;
  a5=0.;
  a6=-4.7917323112487793e+00;
  a7=4.8704517364501953e+01;
  a8=arg[0]? arg[0][0] : 0;
  a9=4.0834456682205200e-01;
  a8=(a8-a9);
  a10=5.7688474655151367e+00;
  a8=(a8/a10);
  a7=(a7*a8);
  a11=-3.0969092249870300e-01;
  a12=arg[0]? arg[0][1] : 0;
  a12=(a12-a9);
  a12=(a12/a10);
  a11=(a11*a12);
  a7=(a7+a11);
  a6=(a6+a7);
  a6=casadi_fmax(a5,a6);
  a4=(a4*a6);
  a7=1.3905100822448730e+01;
  a11=-5.3195466995239258e+00;
  a10=4.3461784362792969e+01;
  a10=(a10*a8);
  a9=6.4302482604980469e+00;
  a9=(a9*a12);
  a10=(a10+a9);
  a11=(a11+a10);
  a11=casadi_fmax(a5,a11);
  a7=(a7*a11);
  a4=(a4+a7);
  a7=3.1158938407897949e+00;
  a10=-4.3991780281066895e+00;
  a9=2.7993044257164001e-01;
  a9=(a9*a8);
  a13=-2.4074411392211914e+00;
  a13=(a13*a12);
  a9=(a9+a13);
  a10=(a10+a9);
  a10=casadi_fmax(a5,a10);
  a7=(a7*a10);
  a4=(a4+a7);
  a7=-4.4989410787820816e-02;
  a9=-7.0028680562973022e-01;
  a13=5.6600314378738403e-01;
  a13=(a13*a8);
  a14=6.4896702766418457e-02;
  a14=(a14*a12);
  a13=(a13+a14);
  a9=(a9+a13);
  a9=casadi_fmax(a5,a9);
  a7=(a7*a9);
  a4=(a4+a7);
  a7=6.7615628242492676e+00;
  a13=-4.7767143249511719e+00;
  a14=-4.3341059684753418e+00;
  a14=(a14*a8);
  a15=2.6609532833099365e+00;
  a15=(a15*a12);
  a14=(a14+a15);
  a13=(a13+a14);
  a13=casadi_fmax(a5,a13);
  a7=(a7*a13);
  a4=(a4+a7);
  a7=-6.0382370948791504e+00;
  a14=6.8650608062744141e+00;
  a15=-2.7623689651489258e+01;
  a15=(a15*a8);
  a16=1.7289382219314575e+00;
  a16=(a16*a12);
  a15=(a15+a16);
  a14=(a14+a15);
  a14=casadi_fmax(a5,a14);
  a7=(a7*a14);
  a4=(a4+a7);
  a7=1.1253526687622070e+01;
  a15=-1.0268412590026855e+01;
  a16=-5.4660911560058594e+01;
  a16=(a16*a8);
  a17=-1.0865424156188965e+01;
  a17=(a17*a12);
  a16=(a16+a17);
  a15=(a15+a16);
  a15=casadi_fmax(a5,a15);
  a7=(a7*a15);
  a4=(a4+a7);
  a7=1.6315197944641113e-01;
  a16=-3.8532027602195740e-01;
  a17=5.9998750686645508e-01;
  a17=(a17*a8);
  a18=1.0757250338792801e-01;
  a18=(a18*a12);
  a17=(a17+a18);
  a16=(a16+a17);
  a16=casadi_fmax(a5,a16);
  a7=(a7*a16);
  a4=(a4+a7);
  a7=2.4235607683658600e-01;
  a17=-7.7172851562500000e-01;
  a18=9.3301039934158325e-01;
  a18=(a18*a8);
  a19=-3.1511865556240082e-02;
  a19=(a19*a12);
  a18=(a18+a19);
  a17=(a17+a18);
  a17=casadi_fmax(a5,a17);
  a7=(a7*a17);
  a4=(a4+a7);
  a7=1.2171204566955566e+01;
  a18=2.6494603157043457e+00;
  a19=-4.8091827392578125e+01;
  a19=(a19*a8);
  a8=-1.6336913108825684e+00;
  a8=(a8*a12);
  a19=(a19+a8);
  a18=(a18+a19);
  a5=casadi_fmax(a5,a18);
  a7=(a7*a5);
  a4=(a4+a7);
  a3=(a3+a4);
  a3=tanh(a3);
  a2=(a2*a3);
  a4=-4.0206313133239746e+00;
  a7=-2.1998226165771484e+01;
  a18=7.0939493179321289e+00;
  a18=(a18*a6);
  a19=9.6543369293212891e+00;
  a19=(a19*a11);
  a18=(a18+a19);
  a19=9.8593034744262695e+00;
  a19=(a19*a10);
  a18=(a18+a19);
  a19=4.6175520867109299e-02;
  a19=(a19*a9);
  a18=(a18+a19);
  a19=3.5359003543853760e+00;
  a19=(a19*a13);
  a18=(a18+a19);
  a19=-4.2198309898376465e+00;
  a19=(a19*a14);
  a18=(a18+a19);
  a19=-4.7084537148475647e-01;
  a19=(a19*a15);
  a18=(a18+a19);
  a19=-2.4026260375976562e+00;
  a19=(a19*a16);
  a18=(a18+a19);
  a19=2.3340030014514923e-01;
  a19=(a19*a17);
  a18=(a18+a19);
  a19=3.2188304901123047e+01;
  a19=(a19*a5);
  a18=(a18+a19);
  a7=(a7+a18);
  a7=tanh(a7);
  a4=(a4*a7);
  a2=(a2+a4);
  a4=3.1772158145904541e+00;
  a18=2.3787719726562500e+01;
  a19=-9.0949115753173828e+00;
  a19=(a19*a6);
  a8=-2.2245164489746094e+02;
  a8=(a8*a11);
  a19=(a19+a8);
  a8=-9.9334249496459961e+00;
  a8=(a8*a10);
  a19=(a19+a8);
  a8=5.2803684026002884e-02;
  a8=(a8*a9);
  a19=(a19+a8);
  a8=-4.2163038253784180e+00;
  a8=(a8*a13);
  a19=(a19+a8);
  a8=-5.2094297409057617e+00;
  a8=(a8*a14);
  a19=(a19+a8);
  a8=-1.5664847373962402e+01;
  a8=(a8*a15);
  a19=(a19+a8);
  a8=1.2507151365280151e+00;
  a8=(a8*a16);
  a19=(a19+a8);
  a8=-4.5339889526367188e+00;
  a8=(a8*a17);
  a19=(a19+a8);
  a8=8.8010501861572266e+00;
  a8=(a8*a5);
  a19=(a19+a8);
  a18=(a18+a19);
  a18=tanh(a18);
  a4=(a4*a18);
  a2=(a2+a4);
  a4=-3.6197478771209717e+00;
  a19=-3.2461505889892578e+01;
  a8=1.3197578191757202e+00;
  a8=(a8*a6);
  a12=6.1682004928588867e+00;
  a12=(a12*a11);
  a8=(a8+a12);
  a12=6.4260601997375488e+00;
  a12=(a12*a10);
  a8=(a8+a12);
  a12=-5.2155818790197372e-02;
  a12=(a12*a9);
  a8=(a8+a12);
  a12=1.1230991363525391e+01;
  a12=(a12*a13);
  a8=(a8+a12);
  a12=4.2468255758285522e-01;
  a12=(a12*a14);
  a8=(a8+a12);
  a12=1.3814413070678711e+01;
  a12=(a12*a15);
  a8=(a8+a12);
  a12=-3.1167197227478027e-01;
  a12=(a12*a16);
  a8=(a8+a12);
  a12=-9.4393754005432129e-01;
  a12=(a12*a17);
  a8=(a8+a12);
  a12=1.2928304672241211e+01;
  a12=(a12*a5);
  a8=(a8+a12);
  a19=(a19+a8);
  a19=tanh(a19);
  a4=(a4*a19);
  a2=(a2+a4);
  a4=-6.7919282913208008e+00;
  a8=-1.0951210021972656e+01;
  a12=3.5819736480712891e+01;
  a12=(a12*a6);
  a20=1.3937015533447266e+00;
  a20=(a20*a11);
  a12=(a12+a20);
  a20=1.0671924591064453e+01;
  a20=(a20*a10);
  a12=(a12+a20);
  a20=-1.6579262912273407e-01;
  a20=(a20*a9);
  a12=(a12+a20);
  a20=3.5234327316284180e+00;
  a20=(a20*a13);
  a12=(a12+a20);
  a20=1.6483241319656372e+00;
  a20=(a20*a14);
  a12=(a12+a20);
  a20=4.9091782569885254e+00;
  a20=(a20*a15);
  a12=(a12+a20);
  a20=-1.2977024316787720e+00;
  a20=(a20*a16);
  a12=(a12+a20);
  a20=4.2387995719909668e+00;
  a20=(a20*a17);
  a12=(a12+a20);
  a20=6.8673956394195557e-01;
  a20=(a20*a5);
  a12=(a12+a20);
  a8=(a8+a12);
  a8=tanh(a8);
  a4=(a4*a8);
  a2=(a2+a4);
  a4=1.4255795478820801e+00;
  a12=-3.1149946212768555e+01;
  a20=7.7671447753906250e+01;
  a20=(a20*a6);
  a21=1.8035778808593750e+02;
  a21=(a21*a11);
  a20=(a20+a21);
  a21=-8.3281593322753906e+00;
  a21=(a21*a10);
  a20=(a20+a21);
  a21=-2.9523426294326782e-01;
  a21=(a21*a9);
  a20=(a20+a21);
  a21=5.3447442054748535e+00;
  a21=(a21*a13);
  a20=(a20+a21);
  a21=-2.0867238998413086e+01;
  a21=(a21*a14);
  a20=(a20+a21);
  a21=-1.7210615158081055e+01;
  a21=(a21*a15);
  a20=(a20+a21);
  a21=1.3901683092117310e+00;
  a21=(a21*a16);
  a20=(a20+a21);
  a21=2.5637820363044739e-01;
  a21=(a21*a17);
  a20=(a20+a21);
  a21=-1.3787109375000000e+02;
  a21=(a21*a5);
  a20=(a20+a21);
  a12=(a12+a20);
  a12=tanh(a12);
  a4=(a4*a12);
  a2=(a2+a4);
  a4=2.4188659191131592e+00;
  a20=3.9262554168701172e+01;
  a21=-1.6342493057250977e+01;
  a21=(a21*a6);
  a22=2.8202819824218750e+01;
  a22=(a22*a11);
  a21=(a21+a22);
  a22=-9.3326997756958008e+00;
  a22=(a22*a10);
  a21=(a21+a22);
  a22=-9.1647043824195862e-02;
  a22=(a22*a9);
  a21=(a21+a22);
  a22=-1.4707123041152954e+00;
  a22=(a22*a13);
  a21=(a21+a22);
  a22=1.9471918106079102e+01;
  a22=(a22*a14);
  a21=(a21+a22);
  a22=1.3080650568008423e+00;
  a22=(a22*a15);
  a21=(a21+a22);
  a22=6.3410151004791260e-01;
  a22=(a22*a16);
  a21=(a21+a22);
  a22=-1.0537919998168945e+00;
  a22=(a22*a17);
  a21=(a21+a22);
  a22=-2.8759881973266602e+01;
  a22=(a22*a5);
  a21=(a21+a22);
  a20=(a20+a21);
  a20=tanh(a20);
  a4=(a4*a20);
  a2=(a2+a4);
  a4=-6.8783264160156250e+00;
  a21=-9.8370828628540039e+00;
  a22=7.0664391517639160e+00;
  a22=(a22*a6);
  a23=-1.7197931289672852e+01;
  a23=(a23*a11);
  a22=(a22+a23);
  a23=1.1092536926269531e+01;
  a23=(a23*a10);
  a22=(a22+a23);
  a23=6.4139291644096375e-02;
  a23=(a23*a9);
  a22=(a22+a23);
  a23=6.8649363517761230e+00;
  a23=(a23*a13);
  a22=(a22+a23);
  a23=-1.2263848304748535e+01;
  a23=(a23*a14);
  a22=(a22+a23);
  a23=1.5720834732055664e+01;
  a23=(a23*a15);
  a22=(a22+a23);
  a23=-3.1308026313781738e+00;
  a23=(a23*a16);
  a22=(a22+a23);
  a23=2.1644845008850098e+00;
  a23=(a23*a17);
  a22=(a22+a23);
  a23=-2.7900424599647522e-01;
  a23=(a23*a5);
  a22=(a22+a23);
  a21=(a21+a22);
  a21=tanh(a21);
  a4=(a4*a21);
  a2=(a2+a4);
  a4=-7.0264863967895508e+00;
  a22=-4.7288291931152344e+01;
  a23=-7.8102364540100098e+00;
  a23=(a23*a6);
  a24=4.6822743415832520e+00;
  a24=(a24*a11);
  a23=(a23+a24);
  a24=-8.8348665237426758e+00;
  a24=(a24*a10);
  a23=(a23+a24);
  a24=2.0501236617565155e-01;
  a24=(a24*a9);
  a23=(a23+a24);
  a24=1.0005973577499390e+00;
  a24=(a24*a13);
  a23=(a23+a24);
  a24=5.3357968330383301e+00;
  a24=(a24*a14);
  a23=(a23+a24);
  a24=-1.0840435791015625e+02;
  a24=(a24*a15);
  a23=(a23+a24);
  a24=-3.3729457855224609e-01;
  a24=(a24*a16);
  a23=(a23+a24);
  a24=-3.0767810344696045e-01;
  a24=(a24*a17);
  a23=(a23+a24);
  a24=7.9266631603240967e-01;
  a24=(a24*a5);
  a23=(a23+a24);
  a22=(a22+a23);
  a22=tanh(a22);
  a4=(a4*a22);
  a2=(a2+a4);
  a4=-4.8891091346740723e+00;
  a23=-3.8562984466552734e+01;
  a24=3.2266569137573242e+00;
  a24=(a24*a6);
  a6=5.4896240234375000e+00;
  a6=(a6*a11);
  a24=(a24+a6);
  a6=7.2795882225036621e+00;
  a6=(a6*a10);
  a24=(a24+a6);
  a6=4.0466379374265671e-02;
  a6=(a6*a9);
  a24=(a24+a6);
  a6=-2.2356789112091064e+00;
  a6=(a6*a13);
  a24=(a24+a6);
  a6=1.3340767621994019e+00;
  a6=(a6*a14);
  a24=(a24+a6);
  a6=5.6598453521728516e+00;
  a6=(a6*a15);
  a24=(a24+a6);
  a6=-3.1395170092582703e-01;
  a6=(a6*a16);
  a24=(a24+a6);
  a6=1.0482409596443176e-01;
  a6=(a6*a17);
  a24=(a24+a6);
  a6=5.2542619705200195e+00;
  a6=(a6*a5);
  a24=(a24+a6);
  a23=(a23+a24);
  a23=tanh(a23);
  a4=(a4*a23);
  a2=(a2+a4);
  a1=(a1+a2);
  a1=(-a1);
  a1=exp(a1);
  a1=(a0+a1);
  a1=(1./a1);
  a2=3.1630816459655762e+00;
  a4=1.5751080513000488e+00;
  a4=(a4*a3);
  a3=4.0206322669982910e+00;
  a3=(a3*a7);
  a4=(a4+a3);
  a3=-3.1772150993347168e+00;
  a3=(a3*a18);
  a4=(a4+a3);
  a3=3.6197476387023926e+00;
  a3=(a3*a19);
  a4=(a4+a3);
  a3=6.7919430732727051e+00;
  a3=(a3*a8);
  a4=(a4+a3);
  a3=-1.4255791902542114e+00;
  a3=(a3*a12);
  a4=(a4+a3);
  a3=-2.4188652038574219e+00;
  a3=(a3*a20);
  a4=(a4+a3);
  a3=6.8783273696899414e+00;
  a3=(a3*a21);
  a4=(a4+a3);
  a3=7.0264878273010254e+00;
  a3=(a3*a22);
  a4=(a4+a3);
  a3=4.8891091346740723e+00;
  a3=(a3*a23);
  a4=(a4+a3);
  a2=(a2+a4);
  a2=(-a2);
  a2=exp(a2);
  a0=(a0+a2);
  a0=(1./a0);
  a1=(a1-a0);
  if (res[0]!=0) res[0][0]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int pendulum_ode_constr_h_e_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int pendulum_ode_constr_h_e_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int pendulum_ode_constr_h_e_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pendulum_ode_constr_h_e_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int pendulum_ode_constr_h_e_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pendulum_ode_constr_h_e_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void pendulum_ode_constr_h_e_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void pendulum_ode_constr_h_e_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int pendulum_ode_constr_h_e_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int pendulum_ode_constr_h_e_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real pendulum_ode_constr_h_e_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pendulum_ode_constr_h_e_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pendulum_ode_constr_h_e_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pendulum_ode_constr_h_e_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pendulum_ode_constr_h_e_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int pendulum_ode_constr_h_e_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
