/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) double_pendulum_ode_cost_ext_cost_e_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[3] = {0, 0, 0};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};

/* double_pendulum_ode_cost_ext_cost_e_fun:(i0[4],i1[],i2[],i3[])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a3, a4, a5, a6, a7, a8, a9;
  a0=-1.1202343702316284e+00;
  a1=-2.1783936023712158e+00;
  a2=5.4658514261245728e-01;
  a3=1.0762728750705719e-01;
  a4=0.;
  a5=-2.0357178151607513e-01;
  a6=3.3313268423080444e-01;
  a7=arg[0]? arg[0][0] : 0;
  a8=1.5695761442184448e+00;
  a7=(a7-a8);
  a9=2.9289009571075439e+00;
  a7=(a7/a9);
  a6=(a6*a7);
  a10=-5.8510441333055496e-02;
  a11=arg[0]? arg[0][1] : 0;
  a11=(a11-a8);
  a11=(a11/a9);
  a10=(a10*a11);
  a6=(a6+a10);
  a10=-3.8600677251815796e-01;
  a12=arg[0]? arg[0][2] : 0;
  a12=(a12-a8);
  a12=(a12/a9);
  a10=(a10*a12);
  a6=(a6+a10);
  a10=2.9283010959625244e-01;
  a13=arg[0]? arg[0][3] : 0;
  a13=(a13-a8);
  a13=(a13/a9);
  a10=(a10*a13);
  a6=(a6+a10);
  a5=(a5+a6);
  a5=casadi_fmax(a4,a5);
  a3=(a3*a5);
  a6=4.9629986286163330e-01;
  a10=2.9648119211196899e-01;
  a9=6.5851223468780518e-01;
  a9=(a9*a7);
  a8=4.3044490739703178e-03;
  a8=(a8*a11);
  a9=(a9+a8);
  a8=-5.6358945369720459e-01;
  a8=(a8*a12);
  a9=(a9+a8);
  a8=-5.3014981746673584e-01;
  a8=(a8*a13);
  a9=(a9+a8);
  a10=(a10+a9);
  a10=casadi_fmax(a4,a10);
  a6=(a6*a10);
  a3=(a3+a6);
  a6=3.6629030108451843e-01;
  a9=5.9453165531158447e-01;
  a8=7.5621682405471802e-01;
  a8=(a8*a7);
  a14=7.1058586239814758e-02;
  a14=(a14*a11);
  a8=(a8+a14);
  a14=-2.7441179752349854e-01;
  a14=(a14*a12);
  a8=(a8+a14);
  a14=-6.3997662067413330e-01;
  a14=(a14*a13);
  a8=(a8+a14);
  a9=(a9+a8);
  a9=casadi_fmax(a4,a9);
  a6=(a6*a9);
  a3=(a3+a6);
  a6=4.8664298653602600e-01;
  a8=-3.0911275744438171e-01;
  a14=-1.3528674840927124e-01;
  a14=(a14*a7);
  a15=5.1324903964996338e-01;
  a15=(a15*a11);
  a14=(a14+a15);
  a15=6.1347734928131104e-01;
  a15=(a15*a12);
  a14=(a14+a15);
  a15=5.4543662071228027e-01;
  a15=(a15*a13);
  a14=(a14+a15);
  a8=(a8+a14);
  a8=casadi_fmax(a4,a8);
  a6=(a6*a8);
  a3=(a3+a6);
  a6=3.4184470772743225e-01;
  a14=8.1543248891830444e-01;
  a15=9.9223917722702026e-01;
  a15=(a15*a7);
  a16=2.6454749703407288e-01;
  a16=(a16*a11);
  a15=(a15+a16);
  a16=7.3798257112503052e-01;
  a16=(a16*a12);
  a15=(a15+a16);
  a16=1.6451366245746613e-01;
  a16=(a16*a13);
  a15=(a15+a16);
  a14=(a14+a15);
  a14=casadi_fmax(a4,a14);
  a6=(a6*a14);
  a3=(a3+a6);
  a6=2.2838400304317474e-01;
  a15=6.2784790992736816e-01;
  a16=4.6463790535926819e-01;
  a16=(a16*a7);
  a17=7.3826169967651367e-01;
  a17=(a17*a11);
  a16=(a16+a17);
  a17=4.5702213048934937e-01;
  a17=(a17*a12);
  a16=(a16+a17);
  a17=-5.4559344053268433e-01;
  a17=(a17*a13);
  a16=(a16+a17);
  a15=(a15+a16);
  a15=casadi_fmax(a4,a15);
  a6=(a6*a15);
  a3=(a3+a6);
  a6=6.1711275577545166e-01;
  a16=2.2111371159553528e-01;
  a17=5.1963281631469727e-01;
  a17=(a17*a7);
  a18=7.9868245124816895e-01;
  a18=(a18*a11);
  a17=(a17+a18);
  a18=-4.9672210216522217e-01;
  a18=(a18*a12);
  a17=(a17+a18);
  a18=9.1529130935668945e-01;
  a18=(a18*a13);
  a17=(a17+a18);
  a16=(a16+a17);
  a16=casadi_fmax(a4,a16);
  a6=(a6*a16);
  a3=(a3+a6);
  a6=4.4649180769920349e-01;
  a17=7.2069782018661499e-01;
  a18=4.7953248023986816e-01;
  a18=(a18*a7);
  a19=3.9458015561103821e-01;
  a19=(a19*a11);
  a18=(a18+a19);
  a19=-5.3334647417068481e-01;
  a19=(a19*a12);
  a18=(a18+a19);
  a19=4.1101759672164917e-01;
  a19=(a19*a13);
  a18=(a18+a19);
  a17=(a17+a18);
  a17=casadi_fmax(a4,a17);
  a6=(a6*a17);
  a3=(a3+a6);
  a6=2.0677554607391357e-01;
  a18=8.6750012636184692e-01;
  a19=6.5618574619293213e-02;
  a19=(a19*a7);
  a20=6.8517640233039856e-02;
  a20=(a20*a11);
  a19=(a19+a20);
  a20=-5.9619998931884766e-01;
  a20=(a20*a12);
  a19=(a19+a20);
  a20=-1.2624643743038177e-01;
  a20=(a20*a13);
  a19=(a19+a20);
  a18=(a18+a19);
  a18=casadi_fmax(a4,a18);
  a6=(a6*a18);
  a3=(a3+a6);
  a6=2.8689417243003845e-01;
  a19=3.4495005011558533e-01;
  a20=7.8861093521118164e-01;
  a20=(a20*a7);
  a7=5.5143815279006958e-01;
  a7=(a7*a11);
  a20=(a20+a7);
  a7=9.3080556392669678e-01;
  a7=(a7*a12);
  a20=(a20+a7);
  a7=-5.4507571458816528e-01;
  a7=(a7*a13);
  a20=(a20+a7);
  a19=(a19+a20);
  a4=casadi_fmax(a4,a19);
  a6=(a6*a4);
  a3=(a3+a6);
  a2=(a2+a3);
  a2=tanh(a2);
  a1=(a1*a2);
  a2=-2.9000060558319092e+00;
  a3=-3.2890506088733673e-02;
  a6=-6.6158376634120941e-02;
  a6=(a6*a5);
  a19=4.6571591496467590e-01;
  a19=(a19*a10);
  a6=(a6+a19);
  a19=1.2500000000000000e-01;
  a19=(a19*a9);
  a6=(a6+a19);
  a19=8.3128154277801514e-02;
  a19=(a19*a8);
  a6=(a6+a19);
  a19=5.6251126527786255e-01;
  a19=(a19*a14);
  a6=(a6+a19);
  a19=5.7343852519989014e-01;
  a19=(a19*a15);
  a6=(a6+a19);
  a19=5.5024957656860352e-01;
  a19=(a19*a16);
  a6=(a6+a19);
  a19=3.0849593877792358e-01;
  a19=(a19*a17);
  a6=(a6+a19);
  a19=4.8768526315689087e-01;
  a19=(a19*a18);
  a6=(a6+a19);
  a19=3.4508249163627625e-01;
  a19=(a19*a4);
  a6=(a6+a19);
  a3=(a3+a6);
  a3=tanh(a3);
  a2=(a2*a3);
  a1=(a1+a2);
  a2=-2.4427375793457031e+00;
  a3=2.9791438579559326e-01;
  a6=1.8786146538332105e-03;
  a6=(a6*a5);
  a19=5.0283443927764893e-01;
  a19=(a19*a10);
  a6=(a6+a19);
  a19=5.9629750251770020e-01;
  a19=(a19*a9);
  a6=(a6+a19);
  a19=5.1227700710296631e-01;
  a19=(a19*a8);
  a6=(a6+a19);
  a19=5.2533096075057983e-01;
  a19=(a19*a14);
  a6=(a6+a19);
  a19=1.8267698585987091e-01;
  a19=(a19*a15);
  a6=(a6+a19);
  a19=3.0036535859107971e-01;
  a19=(a19*a16);
  a6=(a6+a19);
  a19=7.0444601774215698e-01;
  a19=(a19*a17);
  a6=(a6+a19);
  a19=1.5045672655105591e-01;
  a19=(a19*a18);
  a6=(a6+a19);
  a19=6.6776269674301147e-01;
  a19=(a19*a4);
  a6=(a6+a19);
  a3=(a3+a6);
  a3=tanh(a3);
  a2=(a2*a3);
  a1=(a1+a2);
  a2=2.4978768825531006e+00;
  a3=-2.8114836663007736e-02;
  a6=-3.9828515052795410e-01;
  a6=(a6*a5);
  a19=1.0608629323542118e-02;
  a19=(a19*a10);
  a6=(a6+a19);
  a19=-6.5923285484313965e-01;
  a19=(a19*a9);
  a6=(a6+a19);
  a19=-6.0816311836242676e-01;
  a19=(a19*a8);
  a6=(a6+a19);
  a19=-3.3778366446495056e-01;
  a19=(a19*a14);
  a6=(a6+a19);
  a19=-2.1908691525459290e-01;
  a19=(a19*a15);
  a6=(a6+a19);
  a19=-7.1477639675140381e-01;
  a19=(a19*a16);
  a6=(a6+a19);
  a19=-3.0290621519088745e-01;
  a19=(a19*a17);
  a6=(a6+a19);
  a19=-6.1303997039794922e-01;
  a19=(a19*a18);
  a6=(a6+a19);
  a19=-5.4750913381576538e-01;
  a19=(a19*a4);
  a6=(a6+a19);
  a3=(a3+a6);
  a3=tanh(a3);
  a2=(a2*a3);
  a1=(a1+a2);
  a2=-2.3466162681579590e+00;
  a3=4.6176454424858093e-01;
  a6=-4.1291806846857071e-02;
  a6=(a6*a5);
  a19=1.5430629253387451e-01;
  a19=(a19*a10);
  a6=(a6+a19);
  a19=2.7564081549644470e-01;
  a19=(a19*a9);
  a6=(a6+a19);
  a19=2.3493009805679321e-01;
  a19=(a19*a8);
  a6=(a6+a19);
  a19=5.1654320955276489e-01;
  a19=(a19*a14);
  a6=(a6+a19);
  a19=1.5055154263973236e-01;
  a19=(a19*a15);
  a6=(a6+a19);
  a19=3.5634073615074158e-01;
  a19=(a19*a16);
  a6=(a6+a19);
  a19=6.0259932279586792e-01;
  a19=(a19*a17);
  a6=(a6+a19);
  a19=6.1590796709060669e-01;
  a19=(a19*a18);
  a6=(a6+a19);
  a19=3.2400754094123840e-01;
  a19=(a19*a4);
  a6=(a6+a19);
  a3=(a3+a6);
  a3=tanh(a3);
  a2=(a2*a3);
  a1=(a1+a2);
  a2=-1.9425894021987915e+00;
  a3=3.6879181861877441e-01;
  a6=4.1966208815574646e-01;
  a6=(a6*a5);
  a19=4.6860914677381516e-02;
  a19=(a19*a10);
  a6=(a6+a19);
  a19=6.2803649902343750e-01;
  a19=(a19*a9);
  a6=(a6+a19);
  a19=1.0278675705194473e-01;
  a19=(a19*a8);
  a6=(a6+a19);
  a19=6.6282618045806885e-01;
  a19=(a19*a14);
  a6=(a6+a19);
  a19=2.5430387258529663e-01;
  a19=(a19*a15);
  a6=(a6+a19);
  a19=3.3337566256523132e-01;
  a19=(a19*a16);
  a6=(a6+a19);
  a19=5.1499730348587036e-01;
  a19=(a19*a17);
  a6=(a6+a19);
  a19=3.6571431159973145e-01;
  a19=(a19*a18);
  a6=(a6+a19);
  a19=4.3065688014030457e-01;
  a19=(a19*a4);
  a6=(a6+a19);
  a3=(a3+a6);
  a3=tanh(a3);
  a2=(a2*a3);
  a1=(a1+a2);
  a2=2.5106773376464844e+00;
  a3=-2.6513406634330750e-01;
  a6=6.5292857587337494e-02;
  a6=(a6*a5);
  a19=2.0162649452686310e-02;
  a19=(a19*a10);
  a6=(a6+a19);
  a19=-3.2385933399200439e-01;
  a19=(a19*a9);
  a6=(a6+a19);
  a19=-2.8426307439804077e-01;
  a19=(a19*a8);
  a6=(a6+a19);
  a19=-2.5774100422859192e-01;
  a19=(a19*a14);
  a6=(a6+a19);
  a19=-4.7413587570190430e-01;
  a19=(a19*a15);
  a6=(a6+a19);
  a19=-4.4891318678855896e-01;
  a19=(a19*a16);
  a6=(a6+a19);
  a19=-4.2196127772331238e-01;
  a19=(a19*a17);
  a6=(a6+a19);
  a19=-5.9211516380310059e-01;
  a19=(a19*a18);
  a6=(a6+a19);
  a19=-3.5135060548782349e-01;
  a19=(a19*a4);
  a6=(a6+a19);
  a3=(a3+a6);
  a3=tanh(a3);
  a2=(a2*a3);
  a1=(a1+a2);
  a2=2.2508137226104736e+00;
  a3=-5.3714966773986816e-01;
  a6=5.4010167717933655e-02;
  a6=(a6*a5);
  a19=-5.3109866380691528e-01;
  a19=(a19*a10);
  a6=(a6+a19);
  a19=-9.9765695631504059e-02;
  a19=(a19*a9);
  a6=(a6+a19);
  a19=-4.9813807010650635e-02;
  a19=(a19*a8);
  a6=(a6+a19);
  a19=-6.1905974149703979e-01;
  a19=(a19*a14);
  a6=(a6+a19);
  a19=-1.4638485014438629e-01;
  a19=(a19*a15);
  a6=(a6+a19);
  a19=-2.0521724224090576e-01;
  a19=(a19*a16);
  a6=(a6+a19);
  a19=-4.5490142703056335e-01;
  a19=(a19*a17);
  a6=(a6+a19);
  a19=-3.7247875332832336e-01;
  a19=(a19*a18);
  a6=(a6+a19);
  a19=-5.3937631845474243e-01;
  a19=(a19*a4);
  a6=(a6+a19);
  a3=(a3+a6);
  a3=tanh(a3);
  a2=(a2*a3);
  a1=(a1+a2);
  a2=2.0066044330596924e+00;
  a3=-3.8286590576171875e-01;
  a6=-1.4472597837448120e-01;
  a6=(a6*a5);
  a19=-1.8636555969715118e-01;
  a19=(a19*a10);
  a6=(a6+a19);
  a19=-3.1020635366439819e-01;
  a19=(a19*a9);
  a6=(a6+a19);
  a19=-1.4854852855205536e-01;
  a19=(a19*a8);
  a6=(a6+a19);
  a19=-4.3473801016807556e-01;
  a19=(a19*a14);
  a6=(a6+a19);
  a19=-3.4909784793853760e-01;
  a19=(a19*a15);
  a6=(a6+a19);
  a19=-6.2012362480163574e-01;
  a19=(a19*a16);
  a6=(a6+a19);
  a19=-3.0860406160354614e-01;
  a19=(a19*a17);
  a6=(a6+a19);
  a19=-3.6542794108390808e-01;
  a19=(a19*a18);
  a6=(a6+a19);
  a19=-5.1958173513412476e-01;
  a19=(a19*a4);
  a6=(a6+a19);
  a3=(a3+a6);
  a3=tanh(a3);
  a2=(a2*a3);
  a1=(a1+a2);
  a2=2.8370652198791504e+00;
  a3=-9.9971905350685120e-02;
  a6=6.2288697808980942e-02;
  a6=(a6*a5);
  a5=-1.8950480222702026e-01;
  a5=(a5*a10);
  a6=(a6+a5);
  a5=-4.3207690119743347e-01;
  a5=(a5*a9);
  a6=(a6+a5);
  a5=-9.5794396474957466e-03;
  a5=(a5*a8);
  a6=(a6+a5);
  a5=-3.3497133851051331e-01;
  a5=(a5*a14);
  a6=(a6+a5);
  a5=-3.2496958971023560e-01;
  a5=(a5*a15);
  a6=(a6+a5);
  a5=-7.3493081331253052e-01;
  a5=(a5*a16);
  a6=(a6+a5);
  a5=-3.3600878715515137e-01;
  a5=(a5*a17);
  a6=(a6+a5);
  a5=-2.9900193214416504e-01;
  a5=(a5*a18);
  a6=(a6+a5);
  a5=-6.0483539104461670e-01;
  a5=(a5*a4);
  a6=(a6+a5);
  a3=(a3+a6);
  a3=tanh(a3);
  a2=(a2*a3);
  a1=(a1+a2);
  a0=(a0+a1);
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int double_pendulum_ode_cost_ext_cost_e_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int double_pendulum_ode_cost_ext_cost_e_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int double_pendulum_ode_cost_ext_cost_e_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void double_pendulum_ode_cost_ext_cost_e_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int double_pendulum_ode_cost_ext_cost_e_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void double_pendulum_ode_cost_ext_cost_e_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void double_pendulum_ode_cost_ext_cost_e_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void double_pendulum_ode_cost_ext_cost_e_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int double_pendulum_ode_cost_ext_cost_e_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int double_pendulum_ode_cost_ext_cost_e_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real double_pendulum_ode_cost_ext_cost_e_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* double_pendulum_ode_cost_ext_cost_e_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* double_pendulum_ode_cost_ext_cost_e_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* double_pendulum_ode_cost_ext_cost_e_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* double_pendulum_ode_cost_ext_cost_e_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int double_pendulum_ode_cost_ext_cost_e_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
