/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) double_pendulum_ode_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};

/* double_pendulum_ode_expl_ode_fun:(i0[4],i1[2],i2[])->(o0[4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a1=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][1]=a1;
  a2=arg[1]? arg[1][0] : 0;
  a3=arg[1]? arg[1][1] : 0;
  a4=4.2499999999999999e-01;
  a5=arg[0]? arg[0][1] : 0;
  a6=sin(a5);
  a7=(a4*a6);
  a8=4.0250474181105772e-01;
  a9=(a7*a0);
  a10=(a9*a1);
  a11=(a8*a10);
  a12=4.8626491210472871e+00;
  a5=cos(a5);
  a4=(a4*a5);
  a13=(a4*a0);
  a14=(a13*a1);
  a15=(a12*a14);
  a11=(a11-a15);
  a0=(a0+a1);
  a1=-1.4760054800000000e+00;
  a15=(a1*a0);
  a16=-3.3449271905627621e-33;
  a16=(a16*a9);
  a15=(a15-a16);
  a16=4.9009000000000000e+00;
  a17=(a16*a13);
  a15=(a15-a17);
  a17=(a0*a15);
  a11=(a11-a17);
  a17=1.4026793000000001e-01;
  a18=(a17*a0);
  a16=(a16*a9);
  a18=(a18-a16);
  a16=-3.3449271905627628e-33;
  a16=(a16*a13);
  a18=(a18-a16);
  a13=(a13*a18);
  a9=(a9*a15);
  a13=(a13-a9);
  a13=(a3-a13);
  a9=(a17*a13);
  a15=5.1436967529054001e-01;
  a9=(a9/a15);
  a11=(a11+a9);
  a11=(a7*a11);
  a3=(a3-a11);
  a0=(a0*a18);
  a18=6.6544001538978836e-01;
  a11=(a18*a10);
  a9=(a8*a14);
  a11=(a11-a9);
  a0=(a0+a11);
  a11=(a1*a13);
  a11=(a11/a15);
  a0=(a0+a11);
  a0=(a4*a0);
  a3=(a3-a0);
  a2=(a2-a3);
  a3=(a8*a7);
  a18=(a18*a4);
  a3=(a3+a18);
  a18=(a6*a3);
  a12=(a12*a7);
  a8=(a8*a4);
  a12=(a12+a8);
  a8=(a5*a12);
  a18=(a18-a8);
  a8=9.8100000000000005e+00;
  a0=1.2246467991473532e-16;
  a11=-2.0510342851533115e-10;
  a9=arg[0]? arg[0][0] : 0;
  a16=sin(a9);
  a19=(a11*a16);
  a19=(a0*a19);
  a19=(a19-a16);
  a19=(a8*a19);
  a18=(a18*a19);
  a16=-1.7835125000000001e+00;
  a20=(a6*a12);
  a21=(a5*a3);
  a20=(a20+a21);
  a16=(a16-a20);
  a9=cos(a9);
  a11=(a11*a9);
  a0=(a0*a11);
  a0=(a0-a9);
  a8=(a8*a0);
  a16=(a16*a8);
  a18=(a18+a16);
  a16=2.0120634323568890e-09;
  a0=-1.5154394024601179e-28;
  a0=(a0*a7);
  a9=1.5946571253313236e-27;
  a9=(a9*a4);
  a0=(a0+a9);
  a16=(a16*a0);
  a18=(a18-a16);
  a2=(a2-a18);
  a18=3.9410380624999997e-01;
  a12=(a7*a12);
  a3=(a4*a3);
  a12=(a12+a3);
  a18=(a18+a12);
  a2=(a2/a18);
  if (res[0]!=0) res[0][2]=a2;
  a18=(a15*a2);
  a12=(a5*a19);
  a7=(a7*a2);
  a12=(a12-a7);
  a7=(a6*a8);
  a12=(a12+a7);
  a12=(a12-a14);
  a17=(a17*a12);
  a18=(a18+a17);
  a5=(a5*a8);
  a4=(a4*a2);
  a6=(a6*a19);
  a4=(a4+a6);
  a5=(a5-a4);
  a5=(a5+a10);
  a1=(a1*a5);
  a18=(a18+a1);
  a1=1.1181426466372689e-36;
  a18=(a18+a1);
  a13=(a13-a18);
  a13=(a13/a15);
  if (res[0]!=0) res[0][3]=a13;
  return 0;
}

CASADI_SYMBOL_EXPORT int double_pendulum_ode_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int double_pendulum_ode_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int double_pendulum_ode_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void double_pendulum_ode_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int double_pendulum_ode_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void double_pendulum_ode_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void double_pendulum_ode_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void double_pendulum_ode_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int double_pendulum_ode_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int double_pendulum_ode_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real double_pendulum_ode_expl_ode_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* double_pendulum_ode_expl_ode_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* double_pendulum_ode_expl_ode_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* double_pendulum_ode_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* double_pendulum_ode_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int double_pendulum_ode_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
