/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) double_pendulum_ode_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};

/* double_pendulum_ode_expl_vde_adj:(i0[6],i1[6],i2[3],i3[])->(o0[9]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a100, a101, a102, a103, a104, a105, a106, a107, a108, a109, a11, a110, a111, a112, a113, a114, a115, a116, a117, a118, a119, a12, a120, a121, a122, a123, a124, a125, a126, a127, a128, a129, a13, a130, a131, a132, a133, a134, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91, a92, a93, a94, a95, a96, a97, a98, a99;
  a0=2.;
  a1=-2.;
  a2=arg[0]? arg[0][1] : 0;
  a3=(a1*a2);
  a4=arg[0]? arg[0][0] : 0;
  a5=(a0*a4);
  a3=(a3+a5);
  a5=sin(a3);
  a6=3.2000000000000006e-01;
  a7=8.0000000000000004e-01;
  a8=-8.0000000000000004e-01;
  a9=arg[2]? arg[2][1] : 0;
  a10=(a8*a9);
  a10=(a7*a10);
  a10=(a7*a10);
  a10=(a7*a10);
  a11=(a0*a4);
  a12=arg[0]? arg[0][2] : 0;
  a11=(a11-a12);
  a11=(a11-a2);
  a13=cos(a11);
  a14=(a10*a13);
  a15=6.4290816000000028e-01;
  a16=(a0*a4);
  a16=(a16+a12);
  a17=(a0*a2);
  a16=(a16-a17);
  a17=sin(a16);
  a17=(a15*a17);
  a14=(a14+a17);
  a17=6.4000000000000012e-01;
  a18=arg[2]? arg[2][2] : 0;
  a19=(a0*a18);
  a19=(a7*a19);
  a19=(a7*a19);
  a19=(a17*a19);
  a20=(a1*a2);
  a21=(a0*a4);
  a20=(a20+a21);
  a21=cos(a20);
  a22=(a19*a21);
  a14=(a14+a22);
  a22=(a0*a4);
  a22=(a22-a12);
  a23=sin(a22);
  a23=(a15*a23);
  a14=(a14-a23);
  a23=(a0*a2);
  a23=(a23-a12);
  a24=sin(a23);
  a24=(a15*a24);
  a14=(a14-a24);
  a24=5.2428800000000039e-02;
  a25=arg[0]? arg[0][5] : 0;
  a26=casadi_sq(a25);
  a26=(a24*a26);
  a27=(a1*a12);
  a28=(a0*a2);
  a27=(a27+a28);
  a28=sin(a27);
  a29=(a26*a28);
  a14=(a14-a29);
  a29=4.0000000000000002e-01;
  a30=arg[2]? arg[2][0] : 0;
  a31=(a0*a30);
  a31=(a7*a31);
  a31=(a7*a31);
  a31=(a29*a31);
  a31=(a7*a31);
  a32=(a1*a2);
  a32=(a32+a4);
  a32=(a32+a12);
  a33=cos(a32);
  a34=(a31*a33);
  a14=(a14-a34);
  a34=arg[0]? arg[0][3] : 0;
  a35=casadi_sq(a34);
  a35=(a7*a35);
  a35=(a17*a35);
  a35=(a7*a35);
  a35=(a7*a35);
  a35=(a29*a35);
  a35=(a7*a35);
  a36=(a1*a2);
  a36=(a36+a4);
  a36=(a36+a12);
  a37=sin(a36);
  a38=(a35*a37);
  a14=(a14+a38);
  a38=1.6000000000000001e+00;
  a39=(a7*a9);
  a39=(a7*a39);
  a39=(a7*a39);
  a39=(a38*a39);
  a40=(a2-a12);
  a41=cos(a40);
  a42=(a39*a41);
  a14=(a14+a42);
  a42=(a0*a30);
  a42=(a7*a42);
  a42=(a29*a42);
  a43=(a4-a12);
  a44=cos(a43);
  a45=(a42*a44);
  a46=casadi_sq(a34);
  a46=(a8*a46);
  a46=(a7*a46);
  a46=(a7*a46);
  a46=(a29*a46);
  a47=(a4-a12);
  a48=sin(a47);
  a49=(a46*a48);
  a50=arg[0]? arg[0][4] : 0;
  a51=casadi_sq(a50);
  a51=(a38*a51);
  a52=(a2-a12);
  a53=sin(a52);
  a54=(a51*a53);
  a54=(a7*a54);
  a54=(a7*a54);
  a54=(a29*a54);
  a49=(a49-a54);
  a54=3.9240000000000004e+00;
  a55=sin(a12);
  a55=(a54*a55);
  a55=(a7*a55);
  a55=(a29*a55);
  a49=(a49+a55);
  a55=(a0*a18);
  a55=(a38*a55);
  a49=(a49-a55);
  a49=(a7*a49);
  a45=(a45+a49);
  a45=(a7*a45);
  a45=(a7*a45);
  a14=(a14+a45);
  a14=(a14/a29);
  a3=cos(a3);
  a3=(a6*a3);
  a45=1.6000000000000003e-01;
  a49=(a1*a12);
  a55=(a0*a2);
  a49=(a49+a55);
  a55=cos(a49);
  a55=(a45*a55);
  a3=(a3+a55);
  a55=-3.2000000000000006e-01;
  a3=(a3+a55);
  a3=(a3-a6);
  a3=(a3-a45);
  a14=(a14/a3);
  a14=(a14/a3);
  a56=1.2500000000000000e+00;
  a57=1.5624999999999998e+00;
  a58=5.0000000000000000e-01;
  a59=arg[1]? arg[1][5] : 0;
  a59=(a58*a59);
  a59=(a56*a59);
  a59=(a57*a59);
  a59=(a56*a59);
  a14=(a14*a59);
  a60=(a6*a14);
  a5=(a5*a60);
  a60=(a0*a5);
  a47=cos(a47);
  a61=2.5000000000000000e+00;
  a59=(a59/a3);
  a61=(a61*a59);
  a59=(a7*a61);
  a59=(a7*a59);
  a3=(a7*a59);
  a46=(a46*a3);
  a47=(a47*a46);
  a60=(a60+a47);
  a43=sin(a43);
  a42=(a42*a59);
  a43=(a43*a42);
  a60=(a60-a43);
  a36=cos(a36);
  a35=(a35*a61);
  a36=(a36*a35);
  a60=(a60+a36);
  a32=sin(a32);
  a31=(a31*a61);
  a32=(a32*a31);
  a60=(a60+a32);
  a22=cos(a22);
  a31=(a15*a61);
  a22=(a22*a31);
  a31=(a0*a22);
  a60=(a60-a31);
  a20=sin(a20);
  a19=(a19*a61);
  a20=(a20*a19);
  a19=(a0*a20);
  a60=(a60-a19);
  a16=cos(a16);
  a19=(a15*a61);
  a16=(a16*a19);
  a19=(a0*a16);
  a60=(a60+a19);
  a11=sin(a11);
  a10=(a10*a61);
  a11=(a11*a10);
  a10=(a0*a11);
  a60=(a60-a10);
  a10=(a1*a2);
  a19=(a0*a4);
  a10=(a10+a19);
  a19=sin(a10);
  a31=(a1*a18);
  a31=(a7*a31);
  a31=(a7*a31);
  a31=(a7*a31);
  a35=(a0*a4);
  a35=(a35-a12);
  a35=(a35-a2);
  a42=cos(a35);
  a46=(a31*a42);
  a62=1.3107200000000008e-01;
  a63=casadi_sq(a25);
  a63=(a62*a63);
  a64=(a0*a4);
  a64=(a64-a12);
  a64=(a64-a2);
  a65=sin(a64);
  a66=(a63*a65);
  a46=(a46-a66);
  a66=8.0363520000000033e-01;
  a67=(a0*a4);
  a67=(a2+a67);
  a68=(a0*a12);
  a67=(a67-a68);
  a68=sin(a67);
  a68=(a66*a68);
  a46=(a46+a68);
  a68=5.6254464000000022e+00;
  a69=(a0*a4);
  a69=(a69-a2);
  a70=sin(a69);
  a70=(a68*a70);
  a46=(a46-a70);
  a70=casadi_sq(a50);
  a70=(a0*a70);
  a70=(a7*a70);
  a70=(a17*a70);
  a70=(a7*a70);
  a70=(a29*a70);
  a70=(a7*a70);
  a71=(a1*a2);
  a72=(a0*a4);
  a71=(a71+a72);
  a72=sin(a71);
  a73=(a70*a72);
  a46=(a46-a73);
  a73=(a0*a9);
  a73=(a7*a73);
  a73=(a7*a73);
  a73=(a29*a73);
  a74=(a1*a12);
  a75=(a0*a4);
  a74=(a74+a75);
  a75=cos(a74);
  a76=(a73*a75);
  a46=(a46+a76);
  a76=1.3107200000000005e-01;
  a77=casadi_sq(a50);
  a77=(a76*a77);
  a78=(a1*a12);
  a79=(a0*a2);
  a78=(a78+a79);
  a79=sin(a78);
  a80=(a77*a79);
  a46=(a46+a80);
  a80=(a0*a30);
  a80=(a7*a80);
  a80=(a7*a80);
  a80=(a29*a80);
  a81=(a1*a12);
  a81=(a81+a2);
  a81=(a81+a4);
  a82=cos(a81);
  a83=(a80*a82);
  a46=(a46-a83);
  a83=casadi_sq(a34);
  a83=(a76*a83);
  a84=(a1*a12);
  a84=(a84+a2);
  a84=(a84+a4);
  a85=sin(a84);
  a86=(a83*a85);
  a46=(a46+a86);
  a86=1.1200000000000001e+00;
  a87=1.0240000000000002e+00;
  a88=casadi_sq(a34);
  a88=(a87*a88);
  a88=(a86*a88);
  a88=(a7*a88);
  a89=(a4-a2);
  a90=sin(a89);
  a91=(a88*a90);
  a46=(a46-a91);
  a91=(a0*a18);
  a91=(a7*a91);
  a91=(a7*a91);
  a91=(a38*a91);
  a92=(a2-a12);
  a93=cos(a92);
  a94=(a91*a93);
  a46=(a46+a94);
  a94=1.2000000000000002e+00;
  a95=(a0*a30);
  a95=(a7*a95);
  a95=(a94*a95);
  a96=(a4-a2);
  a97=cos(a96);
  a98=(a95*a97);
  a99=6.0000000000000009e-01;
  a100=4.;
  a101=casadi_sq(a25);
  a101=(a100*a101);
  a101=(a29*a101);
  a101=(a7*a101);
  a101=(a99*a101);
  a101=(a7*a101);
  a102=(a2-a12);
  a103=sin(a102);
  a104=(a101*a103);
  a105=1.2556800000000004e+00;
  a106=(a1*a12);
  a106=(a106+a2);
  a107=sin(a106);
  a107=(a105*a107);
  a104=(a104+a107);
  a107=8.7897600000000011e+00;
  a108=sin(a2);
  a108=(a107*a108);
  a104=(a104+a108);
  a108=(a0*a9);
  a108=(a0*a108);
  a104=(a104-a108);
  a104=(a7*a104);
  a98=(a98+a104);
  a98=(a7*a98);
  a46=(a46+a98);
  a10=cos(a10);
  a10=(a6*a10);
  a98=(a1*a12);
  a104=(a0*a2);
  a98=(a98+a104);
  a104=cos(a98);
  a104=(a45*a104);
  a10=(a10+a104);
  a10=(a10+a55);
  a10=(a10-a6);
  a10=(a10-a45);
  a46=(a46/a10);
  a46=(a46/a10);
  a55=arg[1]? arg[1][4] : 0;
  a55=(a58*a55);
  a55=(a57*a55);
  a55=(a56*a55);
  a55=(a56*a55);
  a46=(a46*a55);
  a104=(a6*a46);
  a19=(a19*a104);
  a104=(a0*a19);
  a60=(a60+a104);
  a96=sin(a96);
  a55=(a55/a10);
  a10=(a7*a55);
  a95=(a95*a10);
  a96=(a96*a95);
  a60=(a60-a96);
  a89=cos(a89);
  a88=(a88*a55);
  a89=(a89*a88);
  a60=(a60-a89);
  a84=cos(a84);
  a83=(a83*a55);
  a84=(a84*a83);
  a60=(a60+a84);
  a81=sin(a81);
  a80=(a80*a55);
  a81=(a81*a80);
  a60=(a60+a81);
  a74=sin(a74);
  a73=(a73*a55);
  a74=(a74*a73);
  a73=(a0*a74);
  a60=(a60-a73);
  a71=cos(a71);
  a70=(a70*a55);
  a71=(a71*a70);
  a70=(a0*a71);
  a60=(a60-a70);
  a69=cos(a69);
  a68=(a68*a55);
  a69=(a69*a68);
  a68=(a0*a69);
  a60=(a60-a68);
  a67=cos(a67);
  a68=(a66*a55);
  a67=(a67*a68);
  a68=(a0*a67);
  a60=(a60+a68);
  a64=cos(a64);
  a63=(a63*a55);
  a64=(a64*a63);
  a63=(a0*a64);
  a60=(a60-a63);
  a35=sin(a35);
  a31=(a31*a55);
  a35=(a35*a31);
  a31=(a0*a35);
  a60=(a60-a31);
  a31=(a1*a2);
  a63=(a0*a4);
  a31=(a31+a63);
  a63=sin(a31);
  a68=-8.0363520000000033e-01;
  a70=(a1*a12);
  a73=(a0*a2);
  a70=(a70+a73);
  a70=(a70+a4);
  a73=sin(a70);
  a73=(a68*a73);
  a80=(a0*a12);
  a83=(a0*a2);
  a80=(a80-a83);
  a80=(a80+a4);
  a83=sin(a80);
  a83=(a66*a83);
  a73=(a73-a83);
  a83=(a0*a30);
  a83=(a7*a83);
  a83=(a7*a83);
  a83=(a29*a83);
  a88=(a1*a12);
  a95=(a0*a2);
  a88=(a88+a95);
  a95=cos(a88);
  a104=(a83*a95);
  a73=(a73+a104);
  a104=casadi_sq(a34);
  a104=(a0*a104);
  a104=(a17*a104);
  a104=(a7*a104);
  a104=(a7*a104);
  a104=(a29*a104);
  a104=(a7*a104);
  a108=(a1*a2);
  a109=(a0*a4);
  a108=(a108+a109);
  a109=sin(a108);
  a110=(a104*a109);
  a73=(a73+a110);
  a110=(a0*a18);
  a110=(a7*a110);
  a110=(a7*a110);
  a110=(a7*a110);
  a111=(a1*a2);
  a111=(a111+a4);
  a111=(a111+a12);
  a112=cos(a111);
  a113=(a110*a112);
  a73=(a73-a113);
  a113=(a0*a9);
  a113=(a7*a113);
  a113=(a7*a113);
  a113=(a29*a113);
  a114=(a1*a12);
  a114=(a114+a2);
  a114=(a114+a4);
  a115=cos(a114);
  a116=(a113*a115);
  a73=(a73-a116);
  a116=casadi_sq(a25);
  a116=(a62*a116);
  a117=(a1*a2);
  a117=(a117+a4);
  a117=(a117+a12);
  a118=sin(a117);
  a119=(a116*a118);
  a73=(a73+a119);
  a18=(a0*a18);
  a18=(a7*a18);
  a18=(a7*a18);
  a18=(a7*a18);
  a119=(a4-a12);
  a120=cos(a119);
  a121=(a18*a120);
  a73=(a73+a121);
  a9=(a7*a9);
  a9=(a94*a9);
  a121=(a4-a2);
  a122=cos(a121);
  a123=(a9*a122);
  a124=2.5113600000000007e+00;
  a125=(a1*a2);
  a125=(a125+a4);
  a126=sin(a125);
  a126=(a124*a126);
  a127=casadi_sq(a50);
  a127=(a0*a127);
  a127=(a7*a127);
  a127=(a7*a127);
  a127=(a29*a127);
  a127=(a7*a127);
  a128=(a4-a2);
  a129=sin(a128);
  a130=(a127*a129);
  a126=(a126+a130);
  a130=casadi_sq(a25);
  a130=(a29*a130);
  a131=(a4-a12);
  a132=sin(a131);
  a133=(a130*a132);
  a133=(a7*a133);
  a133=(a7*a133);
  a133=(a29*a133);
  a126=(a126+a133);
  a133=6.2784000000000022e+00;
  a134=sin(a4);
  a134=(a133*a134);
  a126=(a126+a134);
  a30=(a94*a30);
  a126=(a126-a30);
  a126=(a7*a126);
  a123=(a123+a126);
  a123=(a0*a123);
  a123=(a7*a123);
  a73=(a73+a123);
  a73=(a73/a17);
  a73=(a73/a7);
  a31=cos(a31);
  a31=(a6*a31);
  a123=(a1*a12);
  a126=(a0*a2);
  a123=(a123+a126);
  a126=cos(a123);
  a126=(a45*a126);
  a31=(a31+a126);
  a31=(a31-a45);
  a126=-4.8000000000000009e-01;
  a31=(a31+a126);
  a31=(a31-a45);
  a73=(a73/a31);
  a73=(a73/a31);
  a126=arg[1]? arg[1][3] : 0;
  a58=(a58*a126);
  a58=(a56*a58);
  a73=(a73*a58);
  a6=(a6*a73);
  a63=(a63*a6);
  a6=(a0*a63);
  a60=(a60+a6);
  a4=cos(a4);
  a58=(a58/a31);
  a56=(a56*a58);
  a57=(a57*a56);
  a56=(a7*a57);
  a56=(a0*a56);
  a58=(a7*a56);
  a133=(a133*a58);
  a4=(a4*a133);
  a60=(a60+a4);
  a131=cos(a131);
  a4=(a29*a58);
  a4=(a7*a4);
  a4=(a7*a4);
  a130=(a130*a4);
  a131=(a131*a130);
  a60=(a60+a131);
  a128=cos(a128);
  a127=(a127*a58);
  a128=(a128*a127);
  a60=(a60+a128);
  a125=cos(a125);
  a124=(a124*a58);
  a125=(a125*a124);
  a60=(a60+a125);
  a121=sin(a121);
  a9=(a9*a56);
  a121=(a121*a9);
  a60=(a60-a121);
  a119=sin(a119);
  a18=(a18*a57);
  a119=(a119*a18);
  a60=(a60-a119);
  a117=cos(a117);
  a116=(a116*a57);
  a117=(a117*a116);
  a60=(a60+a117);
  a114=sin(a114);
  a113=(a113*a57);
  a114=(a114*a113);
  a60=(a60+a114);
  a111=sin(a111);
  a110=(a110*a57);
  a111=(a111*a110);
  a60=(a60+a111);
  a108=cos(a108);
  a104=(a104*a57);
  a108=(a108*a104);
  a104=(a0*a108);
  a60=(a60+a104);
  a80=cos(a80);
  a66=(a66*a57);
  a80=(a80*a66);
  a60=(a60-a80);
  a70=cos(a70);
  a68=(a68*a57);
  a70=(a70*a68);
  a60=(a60+a70);
  if (res[0]!=0) res[0][0]=a60;
  a49=sin(a49);
  a14=(a45*a14);
  a49=(a49*a14);
  a14=(a0*a49);
  a5=(a1*a5);
  a14=(a14+a5);
  a52=cos(a52);
  a5=(a29*a3);
  a5=(a7*a5);
  a5=(a7*a5);
  a51=(a51*a5);
  a52=(a52*a51);
  a14=(a14-a52);
  a40=sin(a40);
  a39=(a39*a61);
  a40=(a40*a39);
  a14=(a14-a40);
  a39=(a1*a36);
  a14=(a14+a39);
  a39=(a1*a32);
  a14=(a14+a39);
  a27=cos(a27);
  a26=(a26*a61);
  a27=(a27*a26);
  a26=(a0*a27);
  a14=(a14-a26);
  a23=cos(a23);
  a15=(a15*a61);
  a23=(a23*a15);
  a15=(a0*a23);
  a14=(a14-a15);
  a20=(a1*a20);
  a14=(a14-a20);
  a20=(a0*a16);
  a14=(a14-a20);
  a14=(a14+a11);
  a98=sin(a98);
  a46=(a45*a46);
  a98=(a98*a46);
  a46=(a0*a98);
  a14=(a14+a46);
  a19=(a1*a19);
  a14=(a14+a19);
  a2=cos(a2);
  a19=(a7*a10);
  a107=(a107*a19);
  a2=(a2*a107);
  a14=(a14+a2);
  a106=cos(a106);
  a105=(a105*a19);
  a106=(a106*a105);
  a14=(a14+a106);
  a102=cos(a102);
  a101=(a101*a19);
  a102=(a102*a101);
  a14=(a14+a102);
  a14=(a14+a96);
  a92=sin(a92);
  a91=(a91*a55);
  a92=(a92*a91);
  a14=(a14-a92);
  a14=(a14+a89);
  a14=(a14+a84);
  a14=(a14+a81);
  a78=cos(a78);
  a77=(a77*a55);
  a78=(a78*a77);
  a77=(a0*a78);
  a14=(a14+a77);
  a71=(a1*a71);
  a14=(a14-a71);
  a14=(a14+a69);
  a14=(a14+a67);
  a14=(a14+a64);
  a14=(a14+a35);
  a123=sin(a123);
  a45=(a45*a73);
  a123=(a123*a45);
  a45=(a0*a123);
  a14=(a14+a45);
  a63=(a1*a63);
  a14=(a14+a63);
  a14=(a14-a128);
  a125=(a1*a125);
  a14=(a14+a125);
  a14=(a14+a121);
  a121=(a1*a117);
  a14=(a14+a121);
  a14=(a14+a114);
  a121=(a1*a111);
  a14=(a14+a121);
  a108=(a1*a108);
  a14=(a14+a108);
  a88=sin(a88);
  a83=(a83*a57);
  a88=(a88*a83);
  a83=(a0*a88);
  a14=(a14-a83);
  a83=(a0*a80);
  a14=(a14+a83);
  a83=(a0*a70);
  a14=(a14+a83);
  if (res[0]!=0) res[0][1]=a14;
  a49=(a1*a49);
  a12=cos(a12);
  a14=(a29*a3);
  a14=(a7*a14);
  a54=(a54*a14);
  a12=(a12*a54);
  a49=(a49+a12);
  a49=(a49+a52);
  a49=(a49-a47);
  a49=(a49+a43);
  a49=(a49+a40);
  a49=(a49+a36);
  a49=(a49+a32);
  a27=(a1*a27);
  a49=(a49-a27);
  a49=(a49+a23);
  a49=(a49+a22);
  a49=(a49+a16);
  a49=(a49+a11);
  a98=(a1*a98);
  a49=(a49+a98);
  a106=(a1*a106);
  a49=(a49+a106);
  a49=(a49-a102);
  a49=(a49+a92);
  a84=(a1*a84);
  a49=(a49+a84);
  a81=(a1*a81);
  a49=(a49+a81);
  a78=(a1*a78);
  a49=(a49+a78);
  a74=(a1*a74);
  a49=(a49-a74);
  a67=(a0*a67);
  a49=(a49-a67);
  a49=(a49+a64);
  a49=(a49+a35);
  a123=(a1*a123);
  a49=(a49+a123);
  a49=(a49-a131);
  a49=(a49+a119);
  a49=(a49+a117);
  a114=(a1*a114);
  a49=(a49+a114);
  a49=(a49+a111);
  a88=(a1*a88);
  a49=(a49-a88);
  a80=(a0*a80);
  a49=(a49-a80);
  a70=(a1*a70);
  a49=(a49+a70);
  if (res[0]!=0) res[0][2]=a49;
  a49=(a34+a34);
  a48=(a48*a3);
  a48=(a29*a48);
  a48=(a7*a48);
  a48=(a7*a48);
  a48=(a8*a48);
  a49=(a49*a48);
  a48=(a34+a34);
  a37=(a37*a61);
  a37=(a7*a37);
  a37=(a29*a37);
  a37=(a7*a37);
  a37=(a7*a37);
  a37=(a17*a37);
  a37=(a7*a37);
  a48=(a48*a37);
  a49=(a49+a48);
  a48=(a34+a34);
  a90=(a90*a55);
  a90=(a7*a90);
  a86=(a86*a90);
  a87=(a87*a86);
  a48=(a48*a87);
  a49=(a49-a48);
  a48=(a34+a34);
  a85=(a85*a55);
  a85=(a76*a85);
  a48=(a48*a85);
  a49=(a49+a48);
  a34=(a34+a34);
  a109=(a109*a57);
  a109=(a7*a109);
  a109=(a29*a109);
  a109=(a7*a109);
  a109=(a7*a109);
  a109=(a17*a109);
  a109=(a0*a109);
  a34=(a34*a109);
  a49=(a49+a34);
  a34=arg[1]? arg[1][0] : 0;
  a49=(a49+a34);
  if (res[0]!=0) res[0][3]=a49;
  a49=(a50+a50);
  a79=(a79*a55);
  a76=(a76*a79);
  a49=(a49*a76);
  a76=(a50+a50);
  a53=(a53*a5);
  a53=(a38*a53);
  a76=(a76*a53);
  a49=(a49-a76);
  a76=(a50+a50);
  a72=(a72*a55);
  a72=(a7*a72);
  a72=(a29*a72);
  a72=(a7*a72);
  a72=(a17*a72);
  a72=(a7*a72);
  a72=(a0*a72);
  a76=(a76*a72);
  a49=(a49-a76);
  a50=(a50+a50);
  a129=(a129*a58);
  a129=(a7*a129);
  a129=(a29*a129);
  a129=(a7*a129);
  a129=(a7*a129);
  a129=(a0*a129);
  a50=(a50*a129);
  a49=(a49+a50);
  a50=arg[1]? arg[1][1] : 0;
  a49=(a49+a50);
  if (res[0]!=0) res[0][4]=a49;
  a49=(a25+a25);
  a103=(a103*a19);
  a103=(a7*a103);
  a99=(a99*a103);
  a99=(a7*a99);
  a99=(a29*a99);
  a100=(a100*a99);
  a49=(a49*a100);
  a100=(a25+a25);
  a28=(a28*a61);
  a24=(a24*a28);
  a100=(a100*a24);
  a49=(a49-a100);
  a100=(a25+a25);
  a65=(a65*a55);
  a65=(a62*a65);
  a100=(a100*a65);
  a49=(a49-a100);
  a100=(a25+a25);
  a132=(a132*a4);
  a132=(a29*a132);
  a100=(a100*a132);
  a49=(a49+a100);
  a25=(a25+a25);
  a118=(a118*a57);
  a62=(a62*a118);
  a25=(a25*a62);
  a49=(a49+a25);
  a25=arg[1]? arg[1][2] : 0;
  a49=(a49+a25);
  if (res[0]!=0) res[0][5]=a49;
  a44=(a44*a59);
  a44=(a29*a44);
  a44=(a7*a44);
  a44=(a0*a44);
  a33=(a33*a61);
  a33=(a7*a33);
  a33=(a29*a33);
  a33=(a7*a33);
  a33=(a7*a33);
  a33=(a0*a33);
  a44=(a44-a33);
  a97=(a97*a10);
  a97=(a94*a97);
  a97=(a7*a97);
  a97=(a0*a97);
  a44=(a44+a97);
  a82=(a82*a55);
  a82=(a29*a82);
  a82=(a7*a82);
  a82=(a7*a82);
  a82=(a0*a82);
  a44=(a44-a82);
  a58=(a94*a58);
  a44=(a44-a58);
  a95=(a95*a57);
  a95=(a29*a95);
  a95=(a7*a95);
  a95=(a7*a95);
  a95=(a0*a95);
  a44=(a44+a95);
  if (res[0]!=0) res[0][6]=a44;
  a41=(a41*a61);
  a41=(a38*a41);
  a41=(a7*a41);
  a41=(a7*a41);
  a41=(a7*a41);
  a13=(a13*a61);
  a13=(a7*a13);
  a13=(a7*a13);
  a13=(a7*a13);
  a8=(a8*a13);
  a41=(a41+a8);
  a19=(a0*a19);
  a19=(a0*a19);
  a41=(a41-a19);
  a75=(a75*a55);
  a75=(a29*a75);
  a75=(a7*a75);
  a75=(a7*a75);
  a75=(a0*a75);
  a41=(a41+a75);
  a122=(a122*a56);
  a94=(a94*a122);
  a94=(a7*a94);
  a41=(a41+a94);
  a115=(a115*a57);
  a29=(a29*a115);
  a29=(a7*a29);
  a29=(a7*a29);
  a29=(a0*a29);
  a41=(a41-a29);
  if (res[0]!=0) res[0][7]=a41;
  a21=(a21*a61);
  a17=(a17*a21);
  a17=(a7*a17);
  a17=(a7*a17);
  a17=(a0*a17);
  a3=(a38*a3);
  a3=(a0*a3);
  a17=(a17-a3);
  a93=(a93*a55);
  a38=(a38*a93);
  a38=(a7*a38);
  a38=(a7*a38);
  a38=(a0*a38);
  a17=(a17+a38);
  a42=(a42*a55);
  a42=(a7*a42);
  a42=(a7*a42);
  a42=(a7*a42);
  a1=(a1*a42);
  a17=(a17+a1);
  a120=(a120*a57);
  a120=(a7*a120);
  a120=(a7*a120);
  a120=(a7*a120);
  a120=(a0*a120);
  a17=(a17+a120);
  a112=(a112*a57);
  a112=(a7*a112);
  a112=(a7*a112);
  a7=(a7*a112);
  a0=(a0*a7);
  a17=(a17-a0);
  if (res[0]!=0) res[0][8]=a17;
  return 0;
}

CASADI_SYMBOL_EXPORT int double_pendulum_ode_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int double_pendulum_ode_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int double_pendulum_ode_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void double_pendulum_ode_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int double_pendulum_ode_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void double_pendulum_ode_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void double_pendulum_ode_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void double_pendulum_ode_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int double_pendulum_ode_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int double_pendulum_ode_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real double_pendulum_ode_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* double_pendulum_ode_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* double_pendulum_ode_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* double_pendulum_ode_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* double_pendulum_ode_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int double_pendulum_ode_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
