/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) double_pendulum_ode_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[3] = {0, 0, 0};

/* double_pendulum_ode_expl_ode_fun:(i0[6],i1[3],i2[])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a1=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][1]=a1;
  a2=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a2;
  a3=-8.0363520000000033e-01;
  a4=-2.;
  a5=arg[0]? arg[0][2] : 0;
  a6=(a4*a5);
  a7=2.;
  a8=arg[0]? arg[0][1] : 0;
  a9=(a7*a8);
  a6=(a6+a9);
  a9=arg[0]? arg[0][0] : 0;
  a6=(a6+a9);
  a6=sin(a6);
  a3=(a3*a6);
  a6=8.0363520000000033e-01;
  a10=(a7*a5);
  a11=(a7*a8);
  a10=(a10-a11);
  a10=(a10+a9);
  a10=sin(a10);
  a10=(a6*a10);
  a3=(a3-a10);
  a10=4.0000000000000002e-01;
  a11=8.0000000000000004e-01;
  a12=arg[1]? arg[1][0] : 0;
  a13=(a7*a12);
  a13=(a11*a13);
  a13=(a11*a13);
  a13=(a10*a13);
  a14=(a4*a5);
  a15=(a7*a8);
  a14=(a14+a15);
  a14=cos(a14);
  a13=(a13*a14);
  a3=(a3+a13);
  a13=6.4000000000000012e-01;
  a14=casadi_sq(a0);
  a14=(a7*a14);
  a14=(a13*a14);
  a14=(a11*a14);
  a14=(a11*a14);
  a14=(a10*a14);
  a14=(a11*a14);
  a15=(a4*a8);
  a16=(a7*a9);
  a15=(a15+a16);
  a15=sin(a15);
  a14=(a14*a15);
  a3=(a3+a14);
  a14=arg[1]? arg[1][2] : 0;
  a15=(a7*a14);
  a15=(a11*a15);
  a15=(a11*a15);
  a15=(a11*a15);
  a16=(a4*a8);
  a16=(a16+a9);
  a16=(a16+a5);
  a16=cos(a16);
  a15=(a15*a16);
  a3=(a3-a15);
  a15=arg[1]? arg[1][1] : 0;
  a16=(a7*a15);
  a16=(a11*a16);
  a16=(a11*a16);
  a16=(a10*a16);
  a17=(a4*a5);
  a17=(a17+a8);
  a17=(a17+a9);
  a17=cos(a17);
  a16=(a16*a17);
  a3=(a3-a16);
  a16=1.3107200000000008e-01;
  a17=casadi_sq(a2);
  a17=(a16*a17);
  a18=(a4*a8);
  a18=(a18+a9);
  a18=(a18+a5);
  a18=sin(a18);
  a17=(a17*a18);
  a3=(a3+a17);
  a17=(a7*a14);
  a17=(a11*a17);
  a17=(a11*a17);
  a17=(a11*a17);
  a18=(a9-a5);
  a18=cos(a18);
  a17=(a17*a18);
  a3=(a3+a17);
  a17=1.2000000000000002e+00;
  a18=(a11*a15);
  a18=(a17*a18);
  a19=(a9-a8);
  a19=cos(a19);
  a18=(a18*a19);
  a19=2.5113600000000007e+00;
  a20=(a4*a8);
  a20=(a20+a9);
  a20=sin(a20);
  a19=(a19*a20);
  a20=casadi_sq(a1);
  a20=(a7*a20);
  a20=(a11*a20);
  a20=(a11*a20);
  a20=(a10*a20);
  a20=(a11*a20);
  a21=(a9-a8);
  a21=sin(a21);
  a20=(a20*a21);
  a19=(a19+a20);
  a20=casadi_sq(a2);
  a20=(a10*a20);
  a21=(a9-a5);
  a21=sin(a21);
  a20=(a20*a21);
  a20=(a11*a20);
  a20=(a11*a20);
  a20=(a10*a20);
  a19=(a19+a20);
  a20=6.2784000000000022e+00;
  a21=sin(a9);
  a20=(a20*a21);
  a19=(a19+a20);
  a20=(a17*a12);
  a19=(a19-a20);
  a19=(a11*a19);
  a18=(a18+a19);
  a18=(a7*a18);
  a18=(a11*a18);
  a3=(a3+a18);
  a3=(a3/a13);
  a3=(a3/a11);
  a18=3.2000000000000006e-01;
  a19=(a4*a8);
  a20=(a7*a9);
  a19=(a19+a20);
  a19=cos(a19);
  a19=(a18*a19);
  a20=1.6000000000000003e-01;
  a21=(a4*a5);
  a22=(a7*a8);
  a21=(a21+a22);
  a21=cos(a21);
  a21=(a20*a21);
  a19=(a19+a21);
  a19=(a19-a20);
  a21=-4.8000000000000009e-01;
  a19=(a19+a21);
  a19=(a19-a20);
  a3=(a3/a19);
  a3=(a3/a11);
  a3=(a3/a7);
  if (res[0]!=0) res[0][3]=a3;
  a3=(a4*a14);
  a3=(a11*a3);
  a3=(a11*a3);
  a3=(a11*a3);
  a19=(a7*a9);
  a19=(a19-a5);
  a19=(a19-a8);
  a19=cos(a19);
  a3=(a3*a19);
  a19=casadi_sq(a2);
  a16=(a16*a19);
  a19=(a7*a9);
  a19=(a19-a5);
  a19=(a19-a8);
  a19=sin(a19);
  a16=(a16*a19);
  a3=(a3-a16);
  a16=(a7*a9);
  a16=(a8+a16);
  a19=(a7*a5);
  a16=(a16-a19);
  a16=sin(a16);
  a6=(a6*a16);
  a3=(a3+a6);
  a6=5.6254464000000022e+00;
  a16=(a7*a9);
  a16=(a16-a8);
  a16=sin(a16);
  a6=(a6*a16);
  a3=(a3-a6);
  a6=casadi_sq(a1);
  a6=(a7*a6);
  a6=(a11*a6);
  a6=(a13*a6);
  a6=(a11*a6);
  a6=(a10*a6);
  a6=(a11*a6);
  a16=(a4*a8);
  a19=(a7*a9);
  a16=(a16+a19);
  a16=sin(a16);
  a6=(a6*a16);
  a3=(a3-a6);
  a6=(a7*a15);
  a6=(a11*a6);
  a6=(a11*a6);
  a6=(a10*a6);
  a16=(a4*a5);
  a19=(a7*a9);
  a16=(a16+a19);
  a16=cos(a16);
  a6=(a6*a16);
  a3=(a3+a6);
  a6=1.3107200000000005e-01;
  a16=casadi_sq(a1);
  a16=(a6*a16);
  a19=(a4*a5);
  a21=(a7*a8);
  a19=(a19+a21);
  a19=sin(a19);
  a16=(a16*a19);
  a3=(a3+a16);
  a16=(a7*a12);
  a16=(a11*a16);
  a16=(a11*a16);
  a16=(a10*a16);
  a19=(a4*a5);
  a19=(a19+a8);
  a19=(a19+a9);
  a19=cos(a19);
  a16=(a16*a19);
  a3=(a3-a16);
  a16=casadi_sq(a0);
  a6=(a6*a16);
  a16=(a4*a5);
  a16=(a16+a8);
  a16=(a16+a9);
  a16=sin(a16);
  a6=(a6*a16);
  a3=(a3+a6);
  a6=1.1200000000000001e+00;
  a16=1.0240000000000002e+00;
  a19=casadi_sq(a0);
  a16=(a16*a19);
  a6=(a6*a16);
  a6=(a11*a6);
  a16=(a9-a8);
  a16=sin(a16);
  a6=(a6*a16);
  a3=(a3-a6);
  a6=1.6000000000000001e+00;
  a16=(a7*a14);
  a16=(a11*a16);
  a16=(a11*a16);
  a16=(a6*a16);
  a19=(a8-a5);
  a19=cos(a19);
  a16=(a16*a19);
  a3=(a3+a16);
  a16=(a7*a12);
  a16=(a11*a16);
  a17=(a17*a16);
  a16=(a9-a8);
  a16=cos(a16);
  a17=(a17*a16);
  a16=6.0000000000000009e-01;
  a19=4.;
  a21=casadi_sq(a2);
  a19=(a19*a21);
  a19=(a10*a19);
  a19=(a11*a19);
  a16=(a16*a19);
  a16=(a11*a16);
  a19=(a8-a5);
  a19=sin(a19);
  a16=(a16*a19);
  a19=1.2556800000000004e+00;
  a21=(a4*a5);
  a21=(a21+a8);
  a21=sin(a21);
  a19=(a19*a21);
  a16=(a16+a19);
  a19=8.7897600000000011e+00;
  a21=sin(a8);
  a19=(a19*a21);
  a16=(a16+a19);
  a19=(a7*a15);
  a19=(a7*a19);
  a16=(a16-a19);
  a16=(a11*a16);
  a17=(a17+a16);
  a17=(a11*a17);
  a3=(a3+a17);
  a17=(a4*a8);
  a16=(a7*a9);
  a17=(a17+a16);
  a17=cos(a17);
  a17=(a18*a17);
  a16=(a4*a5);
  a19=(a7*a8);
  a16=(a16+a19);
  a16=cos(a16);
  a16=(a20*a16);
  a17=(a17+a16);
  a16=-3.2000000000000006e-01;
  a17=(a17+a16);
  a17=(a17-a18);
  a17=(a17-a20);
  a3=(a3/a17);
  a3=(a3/a11);
  a3=(a3/a11);
  a3=(a3/a13);
  a3=(a3/a7);
  if (res[0]!=0) res[0][4]=a3;
  a3=-8.0000000000000004e-01;
  a17=(a3*a15);
  a17=(a11*a17);
  a17=(a11*a17);
  a17=(a11*a17);
  a19=(a7*a9);
  a19=(a19-a5);
  a19=(a19-a8);
  a19=cos(a19);
  a17=(a17*a19);
  a19=6.4290816000000028e-01;
  a21=(a7*a9);
  a21=(a21+a5);
  a22=(a7*a8);
  a21=(a21-a22);
  a21=sin(a21);
  a21=(a19*a21);
  a17=(a17+a21);
  a21=(a7*a14);
  a21=(a11*a21);
  a21=(a11*a21);
  a21=(a13*a21);
  a22=(a4*a8);
  a23=(a7*a9);
  a22=(a22+a23);
  a22=cos(a22);
  a21=(a21*a22);
  a17=(a17+a21);
  a21=(a7*a9);
  a21=(a21-a5);
  a21=sin(a21);
  a21=(a19*a21);
  a17=(a17-a21);
  a21=(a7*a8);
  a21=(a21-a5);
  a21=sin(a21);
  a19=(a19*a21);
  a17=(a17-a19);
  a19=5.2428800000000039e-02;
  a2=casadi_sq(a2);
  a19=(a19*a2);
  a2=(a4*a5);
  a21=(a7*a8);
  a2=(a2+a21);
  a2=sin(a2);
  a19=(a19*a2);
  a17=(a17-a19);
  a19=(a7*a12);
  a19=(a11*a19);
  a19=(a11*a19);
  a19=(a10*a19);
  a19=(a11*a19);
  a2=(a4*a8);
  a2=(a2+a9);
  a2=(a2+a5);
  a2=cos(a2);
  a19=(a19*a2);
  a17=(a17-a19);
  a19=casadi_sq(a0);
  a19=(a11*a19);
  a19=(a13*a19);
  a19=(a11*a19);
  a19=(a11*a19);
  a19=(a10*a19);
  a19=(a11*a19);
  a2=(a4*a8);
  a2=(a2+a9);
  a2=(a2+a5);
  a2=sin(a2);
  a19=(a19*a2);
  a17=(a17+a19);
  a15=(a11*a15);
  a15=(a11*a15);
  a15=(a11*a15);
  a15=(a6*a15);
  a19=(a8-a5);
  a19=cos(a19);
  a15=(a15*a19);
  a17=(a17+a15);
  a12=(a7*a12);
  a12=(a11*a12);
  a12=(a10*a12);
  a15=(a9-a5);
  a15=cos(a15);
  a12=(a12*a15);
  a0=casadi_sq(a0);
  a3=(a3*a0);
  a3=(a11*a3);
  a3=(a11*a3);
  a3=(a10*a3);
  a0=(a9-a5);
  a0=sin(a0);
  a3=(a3*a0);
  a1=casadi_sq(a1);
  a1=(a6*a1);
  a0=(a8-a5);
  a0=sin(a0);
  a1=(a1*a0);
  a1=(a11*a1);
  a1=(a11*a1);
  a1=(a10*a1);
  a3=(a3-a1);
  a1=3.9240000000000004e+00;
  a0=sin(a5);
  a1=(a1*a0);
  a1=(a11*a1);
  a1=(a10*a1);
  a3=(a3+a1);
  a14=(a7*a14);
  a6=(a6*a14);
  a3=(a3-a6);
  a3=(a11*a3);
  a12=(a12+a3);
  a12=(a11*a12);
  a12=(a11*a12);
  a17=(a17+a12);
  a17=(a17/a10);
  a10=(a4*a8);
  a9=(a7*a9);
  a10=(a10+a9);
  a10=cos(a10);
  a10=(a18*a10);
  a4=(a4*a5);
  a8=(a7*a8);
  a4=(a4+a8);
  a4=cos(a4);
  a4=(a20*a4);
  a10=(a10+a4);
  a10=(a10+a16);
  a10=(a10-a18);
  a10=(a10-a20);
  a17=(a17/a10);
  a17=(a17/a11);
  a17=(a17/a13);
  a17=(a17/a11);
  a17=(a17/a7);
  if (res[0]!=0) res[0][5]=a17;
  return 0;
}

CASADI_SYMBOL_EXPORT int double_pendulum_ode_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int double_pendulum_ode_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int double_pendulum_ode_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void double_pendulum_ode_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int double_pendulum_ode_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void double_pendulum_ode_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void double_pendulum_ode_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void double_pendulum_ode_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int double_pendulum_ode_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int double_pendulum_ode_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real double_pendulum_ode_expl_ode_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* double_pendulum_ode_expl_ode_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* double_pendulum_ode_expl_ode_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* double_pendulum_ode_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* double_pendulum_ode_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int double_pendulum_ode_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
