/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) double_pendulum_ode_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};

/* double_pendulum_ode_expl_ode_fun:(i0[4],i1[2],i2[])->(o0[4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a1=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][1]=a1;
  a2=arg[1]? arg[1][0] : 0;
  a3=4.2499999999999999e-01;
  a4=arg[0]? arg[0][1] : 0;
  a5=cos(a4);
  a6=(a3*a5);
  a7=(a6*a0);
  a8=-8.7349213929892103e-03;
  a9=(a0+a1);
  a10=(a8*a9);
  a11=4.9009000000000000e+00;
  a4=sin(a4);
  a3=(a3*a4);
  a0=(a3*a0);
  a12=(a11*a0);
  a10=(a10-a12);
  a12=(a7*a10);
  a13=-1.6123691172487806e+00;
  a14=(a13*a9);
  a11=(a11*a7);
  a14=(a14-a11);
  a11=(a0*a14);
  a12=(a12-a11);
  a11=-2.2204460492503131e-16;
  a0=(a0*a1);
  a15=(a11*a0);
  a16=3.4694469519536142e-18;
  a7=(a7*a1);
  a1=(a16*a7);
  a15=(a15-a1);
  a15=(a12+a15);
  a1=arg[1]? arg[1][1] : 0;
  a1=(a1-a12);
  a15=(a15+a1);
  a12=-2.2691954159611578e-02;
  a17=(a12*a0);
  a18=4.9007770675810418e+00;
  a19=(a18*a7);
  a17=(a17-a19);
  a14=(a9*a14);
  a17=(a17-a14);
  a14=(a8*a1);
  a19=6.2065688113890405e-01;
  a14=(a14/a19);
  a17=(a17+a14);
  a17=(a3*a17);
  a15=(a15-a17);
  a9=(a9*a10);
  a10=7.1221821903415350e-01;
  a17=(a10*a0);
  a14=(a12*a7);
  a17=(a17-a14);
  a9=(a9+a17);
  a17=(a13*a1);
  a17=(a17/a19);
  a9=(a9+a17);
  a9=(a6*a9);
  a15=(a15-a9);
  a2=(a2-a15);
  a15=-1.7835125000000001e+00;
  a9=(a12*a3);
  a9=(a11-a9);
  a10=(a10*a6);
  a9=(a9-a10);
  a10=(a5*a9);
  a18=(a18*a3);
  a12=(a12*a6);
  a18=(a18+a12);
  a12=(a4*a18);
  a10=(a10-a12);
  a15=(a15+a10);
  a10=9.8100000000000005e+00;
  a12=1.1615685580334619e-16;
  a17=-2.0510342851533115e-10;
  a14=arg[0]? arg[0][0] : 0;
  a20=cos(a14);
  a21=(a17*a20);
  a21=(a12*a21);
  a22=-3.8796683833791976e-17;
  a14=sin(a14);
  a23=(a22*a14);
  a21=(a21-a23);
  a21=(a21-a20);
  a21=(a10*a21);
  a15=(a15*a21);
  a23=(a5*a18);
  a24=(a4*a9);
  a23=(a23+a24);
  a22=(a22*a20);
  a17=(a17*a14);
  a12=(a12*a17);
  a22=(a22+a12);
  a22=(a22-a14);
  a10=(a10*a22);
  a23=(a23*a10);
  a15=(a15-a23);
  a23=2.0120634942366435e-09;
  a22=-1.2206961407182189e-20;
  a22=(a22*a3);
  a14=-1.3859078580071691e-18;
  a14=(a14*a6);
  a22=(a22+a14);
  a23=(a23*a22);
  a15=(a15-a23);
  a2=(a2-a15);
  a15=3.9410380624999997e-01;
  a18=(a3*a18);
  a16=(a16*a3);
  a11=(a11*a6);
  a16=(a16+a11);
  a18=(a18-a16);
  a9=(a6*a9);
  a18=(a18-a9);
  a15=(a15+a18);
  a2=(a2/a15);
  if (res[0]!=0) res[0][2]=a2;
  a15=(a19*a2);
  a18=(a5*a10);
  a3=(a3*a2);
  a18=(a18-a3);
  a3=(a4*a21);
  a18=(a18+a3);
  a18=(a18-a7);
  a8=(a8*a18);
  a15=(a15+a8);
  a5=(a5*a21);
  a6=(a6*a2);
  a4=(a4*a10);
  a6=(a6+a4);
  a5=(a5-a6);
  a5=(a5+a0);
  a13=(a13*a5);
  a15=(a15+a13);
  a13=-1.7451868893041153e-27;
  a15=(a15+a13);
  a1=(a1-a15);
  a1=(a1/a19);
  if (res[0]!=0) res[0][3]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int double_pendulum_ode_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int double_pendulum_ode_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int double_pendulum_ode_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void double_pendulum_ode_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int double_pendulum_ode_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void double_pendulum_ode_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void double_pendulum_ode_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void double_pendulum_ode_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int double_pendulum_ode_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int double_pendulum_ode_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real double_pendulum_ode_expl_ode_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* double_pendulum_ode_expl_ode_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* double_pendulum_ode_expl_ode_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* double_pendulum_ode_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* double_pendulum_ode_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int double_pendulum_ode_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
